### ISSUE TITLE
wl_listener is defined as an opaque pointer

### ISSUE THREAD

**Issue by Timidger** [Smithay/wayland-rs#116]
From what I have seen of most examples in C, when constructing a `wl_listener` to listen for signals a struct is created that has a pointer to `wl_notify_func` (which you define) in the `.notify` field. 

However, in the wayland-sys crate in `server.rs`, it's defined as a opaque pointer which means it can't be constructed by this library directly. Is this a bug? 

Here is the common definition I'm finding in the header files: https://people.freedesktop.org/~whot/wayland-doxygen/wayland/Server/structwl__listener.html

**Comment by vberger** [comment]
This is likely an oversight, as this struct is not directly used by wayland-client or wayland-server...

**Comment by vberger** [comment]
Actually, do you only need `wl_listener`, or do you plan to use the whole `wl_signal` machinery?

I've tried to give a go and expose the `wil_signal_init`/`wl_signal_get`/ etc.. functions, but unfortunately these are defined in the headers of the C libs, and designed to be inlined, as such, they are not exposed in the symbols of the C library. Which means we'd need to re-implement them in rust.

Now, some of them (`wl_signal_get` and `wl_signal_emit`) are built in C using the `wl_list_for_each` macro, itself built using the `wl_container_of` macro. But I don't see how we can implement this `wl_container_of` macro in rust in a way that does not invoke UB. It uses `offsetof`, which we do not have in rust, and I don't see how we can implement it.

**Comment by Timidger** [comment]
I have actually somewhat re implemented those types in my library that uses wayland-rs, so it would be nice to have these here upstream. 

In regards to `wl_container_of`, I have a very unsafe implementation that never the less works. It would only work on `#[repr(C)]`   structs, due to the reordering optimization from the Rust compiler. I don't think these are possible to make safe in a general sense (unless you can guarantee the data passed to the macro is  `#[repr(C)]`, which I don't think you can), but it would be nice if those unsafe primitives were still exposed.

**Comment by vberger** [comment]
I believe this can be closed now. Please open a new issue if you encounter any problem with the implementation. :)
