### ISSUE TITLE
On missing symbol: `WAYLAND_CLIENT_OPTION => None` instead of `panic!`

### ISSUE THREAD

**Issue by broesamle** [Smithay/wayland-rs#118]
Apologies, in case this actually needs to be fixed in glutin -- here was just a one-line-change for me:

Why does `client.rs` use `panic!` here in case of a missing symbol?
```
pub static ref WAYLAND_CLIENT_OPTION: Option<WaylandClient> = {
   match WaylandClient::open("libwayland-client.so") {
      Ok(h) => Some(h),
      Err(::dlib::DlError::NotFound) => None,
      Err(::dlib::DlError::MissingSymbol(s)) => {
         panic!("Found library libwayland-client.so but symbol {} is missing.", s);
      }
   }
}
```
replacing with 
```
Err(::dlib::DlError::MissingSymbol(_)) => None
```
fixed the following issue for me:

Compiling glutin 0.8.1, (with rustup and cargo) fails because there is an older version of `libwayland-client.so` in my system (Linux 16.04):
```
Package: libwayland-client0
Version: 1.9.0-1
```
which does not have `wl_proxy_marshal_array_constructor_versioned`, yet.
Without the panic, glutins `api_dispatch.rs` uses the fallback.

(It could, of course catch the panic, if it is needed here for other reasons.)

**Comment by vberger** [comment]
The original rationale was that if a missing symbol was found, it would probably be a bug in libwayland-sys and the panic would help to catch it.

Now, this is obviously wrong, taking into account old versions of libwayland.

This will be corrected, thanks for reporting it.

**Comment by broesamle** [comment]
Thanks for the quick reply!

.. this is how I quickly fixed it, but, without any further considerations.

https://github.com/broesamle/wayland-rs/commit/176fa9dc6ca77548f19c13de8737813d6cb6997b
