### ISSUE TITLE
Pin version of mdBook

### ISSUE THREAD

**Issue by azerupi** [Smithay/wayland-rs#121]
Hi!

We would like to issue a new release of mdBook containing some changes that could potentially break current books, the config file changed a bit for example. However we found out that a lot of projects automatically deploy using the latest available version and so any breaking update could result in books not being deployed anymore..

We would like to avoid that and recommend pinning the version of mdBook in your deployment script. Cargo supports semver ranges on `cargo install` (right now it issues a deprecation warning, but in the future this warning should go away thanks to rust-lang/cargo#4229)

You can thus simply change `cargo install mdbook` to

```
cargo install mdbook --vers "^0.0.22"
```

Next release will be `0.1.0` and we will try to adhere to semver as much as possible.

For more info, azerupi/mdBook#327 is the tracking issue on our repository.

**Comment by vberger** [comment]
The book has been moved to its own repository and we'll keep an eye on the evolution of this.
