### ISSUE TITLE
The callback's done event does't work in multiple-thread mode.

### ISSUE THREAD

**Issue by fangyuanziti** [Smithay/wayland-rs#122]
I write some code like this when I try to implement a surface handler.

```rust
fn frame(&mut self,
             evqh: &mut EventLoopHandle,
             client: &Client,
             resource: &WlSurface,
             callback: WlCallback) {


        thread::spawn(move || {
            callback.done(mills as u32);
        });
}
```
However, the wayland client can not get the callback done event.

BTW, those code (without a new thread) can work.

```rust
fn frame(&mut self,
             evqh: &mut EventLoopHandle,
             client: &Client,
             resource: &WlSurface,
             callback: WlCallback) {
            callback.done(mills as u32);
}
```

It seems that we can not call `callback.done` in a new thread. I think that will be a problem, because we will store callback and call the done event after some duration when we write a real world compositor.
Do you have some suggestion about this? :smile:

**Comment by vberger** [comment]
Hmm, this is difficult to say with such a small amount of code, as it would depend a lot on what's done around. Do you have a minimal example that can be run and reproduces this issue, including the event-loop setup?

For the matter, calling `callback.done` directly forwards the API call to the wayland C lib, which is supposed to handle it properly. Does the event appear in the trace if you run your server with the `WAYLAND_DEBUG=1` environment variable?

**Comment by fangyuanziti** [comment]
https://github.com/fangyuanziti/wayland-http

All my code placed in this repository. It's a simple compositor with a http API. 

Start server
```bash 
WAYLAND_DEBUG=1 cargo run
```

Test with a client
```bash
WAYLAND_DEBUG=1 weston-simple-damage
```

The `frame` function is placed in src/surface.rs.

**Comment by vberger** [comment]
Okay, I understand your issue.

Using `EventLoop::run()`, your compositor blocks waiting for events coming from the client before processing things further, including flushing your events to the client. And the two processes deadlock each other. You can observe this is you start two instances of `weston-simple-damage` for example, the two clients will generate enough events to make your events loop always make progress.

In your case, as you're not guaranteed to have a regular stream of events causing your event loop to progress forward, you should probably use a more explicit handling, like this:

```rust
loop  {
    // wait for client events for at most 50 miliseconds
    event_loop.dispatch(Some(50)).unwrap();
    display.flush_clients();
}
```

**Comment by vberger** [comment]
`EventLoop::run()` should be better document to reflect this.

**Comment by fangyuanziti** [comment]
You are right. I will change my main loop code. Thanks for work :smile:
