### ISSUE TITLE
Allow handlers in event loops to be removed

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#134]
Currently, it's not possible to remove a handler from an event loop/event queue.

This means that handlers are supposed to be re-used consistently. And using an individual handler for each instance of something implies leaking the handler once the instance is destroyed.

If this event is rare, it's fine to leak one or two objects. But overall it would be better to make handlers removable.

I'm not sure of the best approach. Currently, handlers are stored as a `Vec<Box<Any>>`, and the id provided is just an index in the vec. Meaning either:

- We could simply upgrade to a `Vec<Option<Box<Any>>>`, and setting the option to `None` when the handler is dropped. This raises the question of index reuse: reusing index for future insertion of handlers avoids wasting allocation space, but not reusing index can allow to catch logic bugs more easily.
- We could opt for a fancier solution (which I don't know yet what it could be), involving replacing the id with a more fancy type, in order to allow somehow space reuse while still avoiding Id reuse. This new fancy type should remain `Clone` though.

**Comment by Timidger** [comment]
if you're clear about the fact that IDs are reused, I don't see why the `Vec<Option<Box<Any>>>` approach shouldn't work well. IDs are reused in other libraries I use (wlc, PetGraph, etc.) and I haven't ran into issues because I'm always sure to delete outstanding IDs.

The only other space efficient operation I can think of is to switch the ID over to some type of `UUID` and store the values in a `Hashmap`, but I have a feeling there's a reason why you haven't gone that route.

**Comment by vberger** [comment]
Hmm, I actually realized the real issue with removing handlers. In retrospect that's the real reason I didn't try to make it possible back then.

Each proxy/resource registered to a handler keeps a raw pointer to the memory location of this handler (inside the `Box<_>`). As such, destroying a handler means that if any proxy still exists that was registered to this handler, it will point to freed memory. Not good.

That means I have to make removing a handler `unsafe`. Which on the plus side, is a good way to raise awareness about the fact that you need to do it correctly I guess.

Or I could rework a large part of the internals of the library to make this safe, and it will require some runtime overhead. I much prefer the first option tbh.

**Comment by vberger** [comment]
I've gone the simpler route. Time will tell if it's good as is or needs to be reworked.
