### ISSUE TITLE
Wayland scanner cannot parse KDE server decoration protocol

### ISSUE THREAD

**Issue by Timidger** [Smithay/wayland-rs#158]
Issue found [here](https://github.com/swaywm/wlroots-rs/pull/12#issuecomment-342574102).

EDIT: Reproduced here:
```
thread 'main' panicked at 'Ill-formed protocol file: Some(Ok(CData(
    Copyright (C) 2015 Martin Gräßlin

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 2.1 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
  )))', /home/cosm/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-scanner-0.12.2/src/parse.rs:70:40
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This might be an issue with xml-rs, because I _think_ the XML should be valid.

**Comment by Timidger** [comment]
Ok looks like the issue is [here](https://github.com/Smithay/wayland-rs/blob/master/wayland-scanner/src/parse.rs#L53) where it expects a bunch of characters but in this case got `CData`.

Not sure how you want to refactor this, since the macro panics instead of returning an error. I assume doing a next and matching on the result (e.g bypassing the macro entirely?) I'll try to make a patch doing that, but if you have a better solution that would probably be better since you know your code better.

**Comment by vberger** [comment]
Out of curiosity, how are you using wayland-scanner for wlroot-rs?

I'm wondering because it was never designed to be used without wayland-client/wayland-server.
