### ISSUE TITLE
Xdg Toplevel shell improper positioning

### ISSUE THREAD

**Issue by trimental** [Smithay/wayland-rs#177]
### issue
Hello, I recently ran into a problem with improper positioning of  Xdg Toplevel shells (at least on gnome). 

Through some testing I found that this happens when Xdg Toplevel is used as the shell for wayland surfaces as the problem doesn't occur when using WlShellSurface. I also found that this problem occurs when using alacritty with the wayland backend and not just on the test I did. The wayland server also seems like its trying to close the window.

I'm running Gnome 3.28.2 on Arch and I tested with wayland-client 0.20.10 and wayland-protocols 0.20.10 (with client feature), I'm not sure if this is a gnome bug or a issue with wayland-protocols. I would love to help test if needed as I'm currently trying to learn more about wayland and how wayland rs works. Thank you

### screenshots
![screenshot from 2018-07-06 14-38-34](https://user-images.githubusercontent.com/40879396/42363488-7ac548aa-812a-11e8-941b-b223450d45ec.png)
- Alacritty being rendered on the bottom of the activities view

![screenshot from 2018-07-06 14-38-52](https://user-images.githubusercontent.com/40879396/42363490-7b1f9634-812a-11e8-99ec-0d130d0182f1.png)
- Alacritty being rendered outside of screen

![screenshot from 2018-07-06 14-39-23](https://user-images.githubusercontent.com/40879396/42363491-7b679ace-812a-11e8-9b6e-9da0075ddd4b.png)
- Test application being rendered to the side when only two applications are open which means it does get re-positioned when the activity layout changes

**Comment by vberger** [comment]
> I also found that this problem occurs when using alacritty with the wayland backend and not just on the test I did.

Could you point me to what the test application you used is? This would be greatly helpful to understand what is being wrongly done, and where.

The crates in this repository really only handle the protocol serialization & internal state tracking, as such it is quite unlikely that is issue come from them. However, if alacritty has this issue as well, I'm going to be interested as it'd likely be a bug of [sctk](https://github.com/smithay/client-toolkit).

**Comment by trimental** [comment]
[https://github.com/trimental/waylander](my 'test application') its really just the simple_window example with xdg_shell instead of wl_shell

I don't think its sctk because my test code doesn't use sctk

**Comment by vberger** [comment]
My point is that `xdg_shell` being a slightly more complex protocol than `wl_shell`, simply taking a program written for `wl_shell` and replacing it by `xdg_shell` will likely be subtly wrong.

For example [I recently fixed](https://github.com/Smithay/client-toolkit/commit/a1805b749dd4aa80d48159c52ddd907ddd6d6d28) a bug in SCTK occurring because it was not using the `xdg_surface.set_window_geometry` event. While technically it was optional, many compositors were actually expecting it to be used and behaved poorly if it was absent. And this commit fixed [a bug that is very similar to what you report](https://github.com/Smithay/client-toolkit/issues/8)...

**Comment by trimental** [comment]
I ported alacritty to use sctk 2.4 and it works perfectly thanks

**Comment by vberger** [comment]
So, I guess this can be closed. :)
