### ISSUE TITLE
Scanner cleanup

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#18]
The code of the scanner is currently very messy, and was only designed to have something which works.

It should be cleaned and properly refactored, in order to reuse as much code as possible in the future server side of the generation.

**Comment by vberger** [comment]
The new scanner is much more factored, but could use being cleaner and more commented, so I'll keep this issue.

**Comment by vberger** [comment]
Now, the scanner is mostly tested, which should help.

**Comment by jplatte** [comment]
Potentially helpful for this: https://crates.io/crates/quote

**Comment by jplatte** [comment]
Should this be closed now that #213 has been merged?

**Comment by vberger** [comment]
I guess so :)
