### ISSUE TITLE
Redesign the `user_data` mechanism

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#196]
A very useful functionality  for implementing elaborate servers and client is to associate data to a wayland object (and to clients for server-side).

Currently, this is done via the `set_user_data` and `get_user_data` mechanism, which are obviously terrible as they only deal with `*mut ()`. The goal would be to add a better, more typed interface.

A few questions/constraints remain:

- should it be possible to associate several values to a given object ? (in a typemap kind of way)
  - server-side will need it to be able to associate several values to clients
- the runtime cost should be minimal is no value is actually associated
- to be safe, associated values must be `Send`, as the handles to wayland objects are themselves `Send`, and access to data must be synchronized
  - likely we will need an `unsafe` escape-hatch for non-send data, in the same way that non-`Send` implementations are possible

**Comment by Drakulix** [comment]
From my perspective a typemap is unnecessary, since you may store your own, if you really need one. I would rather keep the code as simple as possible.

**Comment by vberger** [comment]
The need for associating multiple data with `Client`s server-side is real though, even the C libraries have a similar mechanism.

And for objects, I think the bare minimum would be to add typing to the user_data, in an `Any`-like fashion, and with proper synchronization.

**Comment by vberger** [comment]
One option I see for the Proxy/Resource user data would be to have it be set at implementation time (which is guaranteed to occur exactly once before the object is usable). The user data type `UD` would have to be `Send + Sync`, and a `user_data()` method of the proxy/resource would give access to it as a `&UD`. The user can then put a mutex or whatever they want to get interior mutability.

The downside of that is that it completely crosses-out the possibility to put non-`Send` user data (unless creating a wrapper and `unsafe impl`-ing `Send` and `Sync`, which is horrible from an ergonomics point of view.

Or I could introduce a similar "nonsend" dance with the `QueueToken`/`LoopToken`, but to access the user data. Meaning if the user data you stored is not send, you must assert you are accessing it from the correct thread using the token...

**Comment by vberger** [comment]
`Proxy` and `Resource` user data has been done in #198, remains the question of `Client` associated user data.

The problem with `Client` is the question of associating several values to a single `Client`. This will be needed for several modules of `smithay`, or generally anyone that wants to develop a modular compositor. So the question is do we handle this multi-values in wayland-server or let the user handle it themselves (and use a simple `UserData` like for `Resource`s) ? For the record the C wayland libs do provide a mechanism to associate several values to a single `wl_client`.

**Comment by Drakulix** [comment]
I have to say that this sounds very convincing. Also the devs of the c-libs probably have a lot more experience already, so this is an argument in itself.
It is easy to throw the code away, if it turns out to be unnecessary complex, as the mechanism for resources is already in place anyway. I would argue to give this a shot and do a more feature-rich implementation for `Client` with a nice api.
