### ISSUE TITLE
Investigate possible race on global deletion

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#203]
If  the compositor destroys a global at the same time as a client tries to bind it, we can end up with a situation where the client is killed for trying to bind a non-existing global because its request just arrived a little late. There should be some grace period after the destruction of a global.

**Comment by rbjorklin** [comment]
Looks like there's a way for compositors to mitigate this issue now: https://gitlab.freedesktop.org/wayland/wayland/merge_requests/28

**Comment by vberger** [comment]
Oh, nice, thanks for the heads-up. I'll wait for a new version of `libwayland` to be released including this, and add a similar API in `wayland-rs`.

**Comment by primeos** [comment]
In the meantime a new version of `libwayland` (1.18) was [released](https://lists.freedesktop.org/archives/wayland-devel/2020-February/041207.html) that contains [wayland/merge_requests/28]( https://gitlab.freedesktop.org/wayland/wayland/merge_requests/28). Maybe this work could progress now?
(Note: Please only interpret this as an FYI, not a demand or anything like that ;)

**Comment by vberger** [comment]
Thanks for the heads-up!

**Comment by vberger** [comment]
> @vberger if I may ask: Are there some changes in wayland-rs required to fix this issue (above you mentioned "add[ing] a similar API in wayland-rs") or is it mainly open for other people to find until wayland/merge_requests/28 is implemented in every major compositor?

This problem, and the way it has been solved upstream is a purely server-side problem. I keep this issue open on the repo as it needs some implementation on the `wayland-server` crate, so that Wayland compositors built using `wayland-server` can use this fix as well.

Sadly, there is nothing that can be done client-side, apart from waiting major compositors to fix the problem in their codebases.

**Comment by vberger** [comment]
This is implemented in 0.30
