### ISSUE TITLE
container_of might be unsound

### ISSUE THREAD

**Issue by Timidger** [Smithay/wayland-rs#211]
I was running some clippy lints on Way Cooler (which I have never done because I was waiting for it to stabilize) and version of `container_of`, which is used quite a bit in wlroots-rs and is the same implementations [as yours](https://github.com/Smithay/wayland-rs/blob/5e8a10c196fe0735e592f8dcd8ab37b28a2fb8fd/wayland-sys/src/server.rs#L197), reported a very scary looking clippy error:

```
error: casting from `*mut u8` to a more-strictly-aligned pointer (`*mut wlroots_sys::wlr_device`)
  --> src/macros.rs:13:9
   |
13 |           ($ptr as *mut u8).offset(-(offset_of!($container, $field) as isize)) as *mut $container
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | 
  ::: src/backend/session.rs:70:13
   |
70 | /             wl_list_for_each!((*self.session).devices,
71 | |                               link,
72 | |                               (device: wlr_device) => {
73 | |                                   devices.push(Device::from_ptr(device))
74 | |                               });
   | |_________________________________- in this macro invocation
   |
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#cast_ptr_alignment
```

This was fixed by changing the pointer cast from a `*mut u8` to a `usize`, which will bring it in line to the standard c definition.

**Comment by emilio** [comment]
This is not unsound, seems fine to me. Changing it to `usize` will do the incorrect thing. This is fine as long as the container pointer is properly aligned, which it should.

**Comment by Timidger** [comment]
I'm confused why it would do the incorrect thing?

To clarify, the current `isize` would remain, the only change is casting the `$ptr` to a `*mut usize` before attempting to do pointer arithmetic on it.

Especially since the C code uses an equivalent type _and_ clippy threw this up as a hard error on its default settings makes me think that it's only maybe possibly fine.

**Comment by emilio** [comment]
What pointer `offset()` returns depends on the type of the pointer. `offset_of` returns bytes, so you need to call `offset` substracting bytes.

**Comment by vberger** [comment]
As far as I know, the only thing that is actually UB is creating/dereferencing a misaligned pointer, as rustc/llvm emits loads and stores assuming all pointers are always correctly aligned.

Not sure how the warning could be cleanly silenced though, if there is no other subtlety I'm missing making it wrong.
