### ISSUE TITLE
Proper testing on *BSD

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#233]
There is interest for an effort to properly port wayland to the BSD systems. In this direction, it would be nice to manage to effectively test wayland-rs on them (OpenBSD and FreeBSD at least).

**Comment by rennis250** [comment]
I discovered this on OpenBSD today: https://github.com/Smithay/wayland-rs/issues/259

Hope I can help, but will need to read a bit first.

**Comment by rennis250** [comment]
Just to correct the misinformation that I spread: OpenBSD has had EPROTO and other errnos since 6.2. Nix master has recently been upgraded to account for this: https://github.com/nix-rust/nix/pull/1036

**Comment by vberger** [comment]
We now have a CI setup on FreeBSD. Given the CI landscape, I'm not sure if we can easily do better than that, so I'm going to close this for now.
