### ISSUE TITLE
0.23.0 does not compile (error: expected item, found `;`)

### ISSUE THREAD

**Issue by Emmatipate** [Smithay/wayland-rs#253]
I'm having trouble compiling wayland-client on Linux. 

```
$ cargo build                                              
    Updating crates.io index
   Compiling wayland-client v0.23.0
error: expected item, found `;`
  --> [...]/target/debug/build/wayland-client-6ba647aa8660f182/out/wayland_api.rs:19:5
   |
19 |     ;
   |     ^ help: consider removing this semicolon

error: aborting due to previous error

error: Could not compile `wayland-client`.
```

I'm using Arch Linux. I found the problem when I tried to use glutin. I also tested 0.22 and 0.21 and they seem to work.

**Comment by vberger** [comment]
What version of `rustc` do you use, and how do you depend on wayland-client exactly? glutin uses an older version of wayland-client afaik.

**Comment by Emmatipate** [comment]
```$ rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)```

Yeah, from what I understood glutin uses 0.21.

**Comment by vberger** [comment]
Hmm, i cannot reproduce this. Do you have some corrupted files in your `target` directory maybe? Does the issue still occur after a `cargo clean`?

**Comment by Emmatipate** [comment]
Yes, cargo clean does not change anything.

This is the part of wayland_api.rs where the error occurs.
```
# [ doc = "core global object\n\nThe core global object.  This is a special singleton object.  It\nis used for internal Wayland protocol features." ]
pub mod wl_display {
    use std::os::raw::c_char;
    use super::{Proxy, NewProxy, AnonymousObject, Interface, MessageGroup, MessageDesc,
                ArgumentType, Object, Message, Argument, ObjectMetadata, HandledBy, types_null,
                NULLPTR};
    use super::sys::common::{wl_interface, wl_array, wl_argument, wl_message};
    ; // This line
    # [ doc = "global error values\n\nThese errors are global and can be emitted in response to any\nserver request." ]
    # [ repr ( u32 ) ]
    # [ derive ( Copy , Clone , Debug , PartialEq ) ]
    pub enum Error {
        # [ doc = "server couldn\'t find object" ]
        InvalidObject = 0,
        # [ doc = "method doesn\'t exist on the specified interface" ]
        InvalidMethod = 1,
        # [ doc = "server is out of memory" ]
        NoMemory = 2,
        # [ doc ( hidden ) ]
        __nonexhaustive,
    }
```
This code is generated right? Could there be some environment variable or something that is the problem?

**Comment by vberger** [comment]
Well, this line is not generated when I test it, and the code generation should not depend on env variables.

The whole thing is generated from `proc-macro2`, which version of it has cargo chosen for you?

**Comment by Emmatipate** [comment]
0.4.27

**Comment by Emmatipate** [comment]
Side note: when I try to use glutin it attempts to compile wayland-client 0.21.7 and I get a similar error to this one but with a different line number. But if I depend on 0.21.7 directly in my test project I get completely different compile errors.

Also, I don't see why cargo doesn't pick 0.21.11 instead because glutin just depends on "0.21". Maybe some other dependency of glutin has a more specific requirement?

**Comment by vberger** [comment]
> Also, I don't see why cargo doesn't pick 0.21.11 instead because glutin just depends on "0.21". Maybe some other dependency has a more specific requirement.

That surprises me, doesn't `cargo update` fix it?

As for the rest, `0.21.7` has been released for some time and used a lot in the wild, and you're the first one to report such errors, so maybe there is something with your rust installation? Tbh I'm quite lost about what is going on...

**Comment by Emmatipate** [comment]
Oh nevermind now I get 0.21.11 with glutin, but I still get the strange semicolon error even though 0.21.11 worked in my standalone project with only wayland-client.

I did manage to compile my test project using 0.21.7 btw. I just had to add
```
wayland-scanner = "=0.21.7"
wayland-commons = "=0.21.7"
```
to my dependencies. My problem in that case was conflicting nix versions it seems.

**Comment by Emmatipate** [comment]
What makes me most confused is that I get this problem using both `0.21.7` and `0.21.11` when I try to use glutin but only with `0.23.0` when I try to reproduce it in my other test project.

**Comment by Emmatipate** [comment]
For the time being I worked around it using glutin 0.18 => wayland-client 0.20.12.

**Comment by Emmatipate** [comment]
[Here is my entire wayland_api.rs](https://gist.github.com/Emmatipate/e080d93bd675d45ccdaf6a427892f7ce). I compared it to one from a friend who managed to compile without problems. The order of statements is not entirely the same but I think he has `use super::sys::client::*;` where I only have `;`.

I noticed another strange thing. I get extra spaces inside of attributes. Instead of `#[...]` I get `# [ ... ]`.

For example I have:
```
    # [ doc = "global error values\n\nThese errors are global and can be emitted in response to any\nserver request." ]
    # [ repr ( u32 ) ]
    # [ derive ( Copy , Clone , Debug , PartialEq ) ]
```
where my friend has:
```
    #[doc = "global error values\n\nThese errors are global and can be emitted in response to any\nserver request."]
    #[repr(u32)]
    #[derive(Copy, Clone, Debug, PartialEq)]
```

**Comment by jplatte** [comment]
@Emmatipate What version of `rustfmt` do you have installed?

**Comment by Emmatipate** [comment]
0.6.3

**Comment by Emmatipate** [comment]
Ok it seems like that was the problem. I realized I had two versions of rustfmt installed. rustfmt  `0.6.3` in ~/.cargo/bin and `1.0.0-stable (43206f4 2018-11-30)` in /usr/bin. I uninstalled the one in ~/.cargo/bin and now it works! :)
