### ISSUE TITLE
build script should notify cargo of their dependency on protocol files

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#255]
Quoting @jplatte:

> You want to `println!("cargo:rerun-if-changed={}", protocol_file);` (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script)

So that the build script is re-run if the protocol file changes

**Comment by jplatte** [comment]
Small correction: so that the build script is *only* re-run if the protocol file changes. Not specifying any file dependencies results in cargo always re-running the build script; specifying them limits this to when `build.rs` or a specified dependency changes.
