### ISSUE TITLE
OpenBSD: No EPROTO errno

### ISSUE THREAD

**Issue by rennis250** [Smithay/wayland-rs#259]
Hello,

There are a few locations in the code that now check for an EPROTO result (EPROTO is from the nix crate). EPROTO is not available via nix on OpenBSD, so the build fails, causing newer versions of the previously working glium/glutin to not build. I will try to read on how to correct this, but I am not familiar enough yet.

Best,
Rob

**Comment by vberger** [comment]
Have the C libwayland-client.so been ported to OpenBSD? And if so what does it use in place of EPROTO?

**Comment by rennis250** [comment]
There was some work on porting it:

https://github.com/jasperla/openbsd-wip/tree/master/x11/wayland-protocols
https://github.com/jasperla/openbsd-wip/tree/master/x11/wayland

but not since almost a year at the latest.

For the time being, I am using an older version of Glium (v0.20), which depends on wayland-client v0.12. That builds and works for me here.

My quick search about OpenBSD's EPROTO shows that it was added in 6.2 (https://man.openbsd.org/OpenBSD-6.2/errno).

Looking at the code for nix, it seems rather that they just don't include EPROTO when compiling it on OpenBSD, so I will notify them:

https://github.com/nix-rust/nix/blob/7bcd9d2318602553c6bd917a4e552a580f9156bb/src/errno.rs

Sorry for the noise!

--Rob

**Comment by rennis250** [comment]
Issue opened: https://github.com/nix-rust/nix/issues/1039

**Comment by rennis250** [comment]
Actually, I was wrong about the whole EPROTO thing and need to correct the misinformation I spread. It turns out EPROTO and other new errnos have been available in OpenBSD since 6.2. Nix master was recently upgraded to account for that: nix-rust/nix#1036
