### ISSUE TITLE
wayland-protocols documents backward-incompatible changes

### ISSUE THREAD

**Issue by emersion** [Smithay/wayland-rs#260]
[The docs](https://docs.rs/wayland-protocols/0.23.1/wayland_protocols/unstable/index.html) say that:

>The protocols described in this module are experimental and backward incompatible changes may be made.

That's not true. Backward incompatible changes to unstable protocols won't be made. Instead, a new protocol will be published with a different name (typically the version suffix is bumped, e.g. `_v2` → `_v3`).

**Comment by vberger** [comment]
Thanks for the heads-up. This note was written quite some time ago and never really reviewed.

**Comment by emersion** [comment]
Thanks for the fix! This applies to wlr-protocols as well.
