### ISSUE TITLE
Build error updating wayland-rs

### ISSUE THREAD

**Issue by Timidger** [Smithay/wayland-rs#261]
For Way Cooler we [updated wayland-rs](https://github.com/way-cooler/way-cooler/pull/608) and ran into a [build error](https://builds.sr.ht/~timidger/job/58542).

It's reproducible on my local machine as well, not sure what the problem is but it looks like it's on your end.

The feature flags used are defined [here](https://github.com/way-cooler/way-cooler/pull/608/files#diff-e5ad2453fe9aed18fec0a65aa087da96). Note that `wayland-sys` as a direct dependency is not necessary any more but removing it does not fix the build.

**Comment by vberger** [comment]
This is quite weird here is that your build system seems to be compiling both `wayland-sys` version 0.23.3 and version **0.12.5**, the latter being the failing one... ?

**Comment by Timidger** [comment]
Ah, nice catch. Let me check my dependency tree and see how that happened.

**Comment by Timidger** [comment]
Ah, was being pulled in from an old copy of wlroots-rs. Sorry for the noise.
