### ISSUE TITLE
Getting id from a Main

### ISSUE THREAD

**Issue by johan-bjareholt** [Smithay/wayland-rs#276]
I couldn't find an IRC or anyplace else to ask a question, so I'll do it here in a GitHub issue even though it's probably not the suitable place.

So I'm currently writing a program implementing the wlr-foreign-toplevel-management protocol from rootston which works fine as of now and I'm able to get the title, appid and state of all currently open windows.

The issue however is that if you get a title change for a window, you do not know which window it was that changed the title as I can't access the ID. What I get from assign_mono is a Main object which implements Proxy but the Proxy implementation is within the inner object so I'm unable to actually get the ID even though it's hidden inside the private inner field.

So what I need is the ability to access the ID property from a Main.

This could be implemented in a number of ways, such as adding the ability to downcast the Main to a Proxy or to implement all Proxy functions for main. Maybe this is already possible somehow but I just can't figure out how? I have been digging quite a lot to find such an example and been unable to though.

**Comment by vberger** [comment]
Looks like you found a place where the documentation is lacking.

The inner objects (`I: Interface`) all implement `AsRef<Proxy<I>>`, as such given an `I` or a `Main<I>`, you can access the underlying `Proxy<I>` by first calling the `as_ref()` method, which will give you the associated `&Proxy<I>`.

Note that the `Proxy<I>` also implement `PartialEq`, which will be more robust to test equality of two objects than relying on comparing the IDs, as the wayland protocol reuses IDs.

**Comment by vberger** [comment]
Also, there is a chatroom, it can be accessed as either:

- [`#smithay:matrix.org`](https://matrix.to/#/#smithay:matrix.org) in Matrix
- `#smithay` on Freenode IRC
- [`Smithay/Lobby`](https://gitter.im/smithay/Lobby) on Gitter

All of them are bridged together, so are actually the same chatroom. I'll add it to the Readme.

**Comment by johan-bjareholt** [comment]
Awesome! Will test it out in a day or two when I have time.

**Comment by johan-bjareholt** [comment]
Works great, thanks!

Will push the code to github when I have cleaned it up.

Created a PR to add the chatrooms to the readme.
