### ISSUE TITLE
Does wayland support pixmaps?

### ISSUE THREAD

**Issue by goddessfreya** [Smithay/wayland-rs#281]
@vberger

**Comment by goddessfreya** [comment]
Nvm, found it:

>   It is not valid to call eglCreatePlatformPixmapSurface with a <dpy> that
    belongs to Wayland. Any such call fails and generates an
    EGL_BAD_PARAMETER error.

**Comment by vberger** [comment]
Glad you found out yourself, because I'd not have been able to answer this one. My knowledge about EGL is superficial at best. :sweat_smile:
