### ISSUE TITLE
Removal of `eventloop` feature on `wayland-client` undocumented.

### ISSUE THREAD

**Issue by goddessfreya** [Smithay/wayland-rs#285]

**Comment by vberger** [comment]
Hm, indeed, the `eventloop` cargo feature was removed in 0.24 as described in the [release notes](https://github.com/Smithay/wayland-rs/releases/tag/v0.24.0):

> **No more event loop integration**
> 
> calloop is no longer a dependency of wayland-rs, and instead the structures of the library provide basic methods (get_fd() and dispatch()) allowing you to proceed with the integration into an other event loop as you prefer.

I'm not sure I understand what more this issue is about... ?

**Comment by goddessfreya** [comment]
Ah, I see. I was grepping the changelog for `eventloop`- I guess if I grepped for `event loop` I would have spotted that. My bad.
