### ISSUE TITLE
`offset_of` is indeed UB

### ISSUE THREAD

**Issue by kazcw** [Smithay/wayland-rs#288]
There's a `offset_of!` impl here: https://github.com/Smithay/wayland-rs/blob/ff15bdce3410f26d84cdf603b484b3b712bc8620/wayland-sys/src/server.rs#L198

There is no sound way to implement `offset_of!` until [RFC 2582](https://rust-lang.github.io/rfcs/2582-raw-reference-mir-operator.html) lands. The validity rule run afoul of in this case is described in the RFC:

> references must be aligned and dereferencable, even when they are created and never used.

**Comment by RalfJung** [comment]
FWIW, the [memoffset crate](https://github.com/Gilnaa/memoffset/) provides a version of this macro that avoids UB (on older versions of rustc, this is not always possible, so it falls back to the 'least incorrect' version when needed).

**Comment by vberger** [comment]
For the record, the ongoing rewrite in #381 is using the memoffset crate. :)

**Comment by vberger** [comment]
Latest released version is also using `memoffset` now, so closing this.
