### ISSUE TITLE
impl Sync for ProxyInner is unsound

### ISSUE THREAD

**Issue by kazcw** [Smithay/wayland-rs#289]
There are various ways to read and write the `wrapping` field of native `ProxyInner` without synchronization. For example: `ProxyInner::clone` reads `.wrapping`; `ProxyInner::attach` writes `.wrapping`. `Proxy::attach` calls both methods, without synchronization (and `Proxy` is `Send+Sync`, because both field `ProxyInner`, and the `PhantomData<&'static Interface>` are). So: if someone puts a `Proxy` in a `Arc` and shares it between two threads, and both threads call `attach`, a data race has been triggered from safe code.

**Comment by vberger** [comment]
`ProxyInner::attach` requires `&mut self`, so it cannot be called concurently on the same instance of `ProxyInner`.

For `Proxy::attach`, it first clones the `Proxy`, and then calls `ProxyInner::attach` on the cloned proxy before returning it. So even if the method is called on the same proxy from several, these are different `ProxyInner` instances that are modified.

**Comment by kazcw** [comment]
Oh of course. Don't mind me...
