### ISSUE TITLE
ThreadGuard unsound for Drop types

### ISSUE THREAD

**Issue by kazcw** [Smithay/wayland-rs#290]
ThreadGuard doesn't guard against `drop(&mut self)` in the wrong thread.

```Rust
fn main() {
    use std::rc::Rc;
    let rc = Rc::new(());
    for _ in 0..100 {
        let foo = ThreadGuard::new(Rc::clone(&rc));
        std::thread::spawn(move || {
            std::mem::drop(foo);
        });
    }
    println!("{}", Rc::strong_count(&rc));
}
```

I get nondeterministic results, including segfaults.

**Comment by vberger** [comment]
I guess for this one, there is no other way to make it safe than to internally call `ManuallyDrop`, and only call the `Drop` implementation if we are on the right thread, right?

That would mean leaking values if they are dropped on the wrong thread, but this wrapper is only meant to help the internals of wayland-client, where objects are stored on a single structure access from all threads, but their callbacks should only be called from the right thread.
