### ISSUE TITLE
Replace the xcur crate for parsing XCursor files

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#309]
The `xcur` crate currently used by `wayland-cursor` seems to contains some bugs. See for example the following code:

```rust
use std::io::Read;
fn main() {
    let mut data = Vec::new();
    let mut file = std::fs::File::open("/usr/share/icons/Adwaita/cursors/left_ptr").unwrap();
    file.read_to_end(&mut data);
    let (_, cur) = xcur::parser::File::parse(&data).unwrap();
    println!("{:#?}", cur.images[0]);
}
```

Produces the following output for me:

```
Image {
    chunkheader: ChunkHeader {
        header: 36,
        type_: 4294770690,
        subtype: 24,
        version: 1,
    },
    width: 24,
    height: 24,
    xhot: 4,
    yhot: 4,
    delay: 50,
    pixels: [
        4,
        4,
        50,
        0,
        0,
        0,
        0,
        0,
...
```

Notably, the first 3 pixels look suspiciously like the `xhot`, `yhot` and `delay` have been erroneously re-parsed. This causes a 3-pixels offset into the rest of the image, that is noticeable and has been initially reported by @kchibisov.

cc @esposm03 , did you have in your plans to integrate a parser in your `xcursor` crate?

**Comment by esposm03** [comment]
> did you have in your plans to integrate a parser in your xcursor crate?
I did, but it was a low-priority thing as I hadn't noticed any issues with `xcur` while testing. Will do that now.
