### ISSUE TITLE
Build failed on code coverage test

### ISSUE THREAD

**Issue by M-Adoo** [Smithay/wayland-rs#314]
Build failed in ci env (github action), runs-on `ubuntu-latest`.

Output:
```
error: failed to run custom build command for `wayland-client v0.23.6`
##[error]failed to run custom build command for `wayland-client v0.23.6`
Caused by:
  process didn't exit successfully: `/home/runner/work/Holiday/Holiday/target/debug/build/wayland-client-d6fb7ac1cff2eace/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stdout
cargo:rerun-if-changed=./wayland.xml

warning: build failed, waiting for other jobs to finish...
##[warning]error: build failed
##[error]The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```

Run `cargo test ` with below arguments:
```
CARGO_INCREMENTAL=0
RUSTFLAGS = "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
```

more detail: https://github.com/M-Adoo/Holiday/pull/9/checks?check_run_id=656948665

**Comment by vberger** [comment]
Well, that's extremely difficult to guess what causes the build script to `SIGABRT` like that. `wayland-client`'s build script is just a codegen script, it reads an XML files and generates a rust source file, that's about it.

Given you are using `panic=abort`, I suspect the build script is actually panicking? If that's the case, that'll be difficult to pinpoint the issue without the panic message and associated stacktrace.

**Comment by M-Adoo** [comment]
Yes.  The weird thing is that  if I remove `panic=abort`, it will build successfully.

**Comment by vberger** [comment]
Indeed, I can reproduce on rust stable. Just setting `RUSTFLAGS="-Cpanic=abort"` makes the build script fail. Interesting.

**Comment by vberger** [comment]
Ok, this is caused by this : https://github.com/alexcrichton/proc-macro2/issues/218
