### ISSUE TITLE
A simple window example without wl_shell

### ISSUE THREAD

**Issue by PonasKovas** [Smithay/wayland-rs#315]
I don't know much about other major wayland compositors, but Sway doesn't support `wl_shell`, while the [current simple window example](https://github.com/Smithay/wayland-rs/blob/master/wayland-client/examples/simple_window.rs) depends on it.

wl_shell is deprecated and using it in examples is wrong.

Can a simple window example that does not depend on `wl_shell` be arranged?

**Comment by vberger** [comment]
It can be done, but it'd require the wayland-protocols crate for the xdg-shell protocol. Not sure if cargo supports cyclic dependencies for examples like that?

**Comment by kchibisov** [comment]
note, if the end goal is to write wayland client in rust, you can take a look on https://github.com/smithay/client-toolkit

**Comment by PonasKovas** [comment]
@vberger I didn't really understand what you meant, but adding this to `wayland-client`'s `Cargo.toml`:
```toml
[dev-dependencies]
wayland-protocols = { version = "0.26.4", path = "../wayland-protocols" }
```
and then just using the crate `wayland-protocols` in `examples/simple_window.rs` works fine for me.

**Comment by PonasKovas** [comment]
Has there been any progress? I'm kinda waiting for this so I can refer to a proper example while porting my own application to wayland.

**Comment by vberger** [comment]
Proper and complete support of the `xdg_shell` protocol extension requires much more complex processing than `wl_shell`, and I clearly don't have the bandwidth to write a detailed example handling this right now, sorry.

However, if your goal is to port an app to Wayland, I'd suggest looking at [SCTK](https://docs.rs/smithay-client-toolkit/), which is a toolkit that abstracts away a significant part of the Wayland protocol complexity, including the shell protocols handling.
