### ISSUE TITLE
Crates organization & backend abstraction

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#317]
I'm re-opening an issue about this to collect thoughts, given a few persons seemed recently interested in improving the API design of wayland-rs (cc @tadeokondrak, @Matthias-Fauconneau).

Currently, wayland-rs is still in tension between two goals:

- designing an API for the Wayland protocol that is as convenient to use as possible from Rust
- keep compatibility with the system C libraries, whose API is not really rust-friendly

The current state is the result of some trade-off between those two, though it's still probably more tailored to the C lib than it should.

So I'd been thinking a few months ago to try an create some kind of "backend abstraction layer", that would be the most minimal & low-level API possible, that would still be implementable both in Rust and on top of the C `libwayland`. From this very low level primitive, it'd then be possible to build an higher-level API that would be more adapted to the Rust language, probably. Though I feel I've kind of exhausted my imagination wrt that for now.

Anyway, this low-level API I imagined looks like that:

```rust
/*
 * Common types
 */

/// Description of the protocol-level information of an object
pub struct ObjectInfo {
    /// The protocol ID
    id: u32,
    /// The interface
    interface: &'static str,
    /// The version
    version: u32,
}

/// A trait representing your data associated to an object
///
/// You will only be given access to it as a `&` reference, so you
/// need to handle interior mutability by yourself.
///
/// The methods of this trait will be invoked internally every time a
/// new object is created to initialize its data.
pub trait ObjectData {
    /// Create a new object data from the parent data
    fn from_parent(my_info: &ObjectInfo, parent_info: &ObjectInfo, parent_data: &Self)
        -> Self;
    /// Create a new object data for an object without parent
    fn from_nothing(my_info: &ObjectInfo) -> Self;
}

// As well as the protocol descriptions for wayland-commons
pub trait Interface { ... }
pub struct Message { ... }
// ....

/// Core trait for representing a Wayland client
///
/// This is the bare minimum API to represent interaction with the
/// Wayland protocol. In particular everything centers around this
/// object representing the connection. Any kind of multi-thread support
/// or dispatching of messages accross several queues must be implemented
/// at a higher level, by sharing this object using `Arc<RwLock<_>>` or
/// something equivalent depending on your goal.
///
/// A well-behaved implementation of this trait should be `Send` as long as
/// its `ObjData` type parameter is.
pub trait WaylandCoreClient<ObjData: ObjectData> {
    type ObjectId: Clone;
  
    /// Initialize the wayland state on a connected unix socket
    fn connect(fd: RawFd) -> Result<Self, ConnectError>;
  
    /// Get the `wl_display` id
    fn display_id(&self) -> ObjectId;
  
    /// Retrieve the last error that occured if the connection
    /// is in an error state
    fn last_error(&self) -> Option<WaylandError>;

    /// Get the connection FD for monitoring using epoll or equivalent
    fn connection_fd(&self) -> RawFd;
    
    /// Create a new client-side object
    ///
    /// If a parent is provided, the `ObjectData` will be inititialized using
    /// `ObjectData::from_parent` with the parent's information. Otherwise, it'll be
    /// initialized using `ObjectData::from_nothing`.
    ///
    /// The version of the created object is chosen as:
    ///
    /// - the provided `version` if it is not `None`
    /// - otherwise the `parent`'s version if it is not `None`
    /// - otherwise `1`
    fn create_object::<I: Interface>(
        &mut self,
        parent: Option<&ObjectId>,
        version: Option<u32>
    ) -> Self::ObjectId;
    
    /// Access the protocol-level information associated with this object
    ///
    /// Returns `None` if the object id is no longer valid.
    fn object_info(&self, id: &Self::ObjectId) -> Option<&ObjectInfo>;
    
    /// Access your `ObjectData` associated with this object
    ///
    /// The object data is initialized by when the
    /// object is created, and you are responsible for any interior mutability.
    ///
    /// Returns `None` if the object is no longer valid.
    fn object_data(&self, id: &Self::ObjectId) -> Option<&ObjData>;
  
    /// Send given message on given object
    ///
    /// If this message should create a new object, you need to first create it
    /// with `create_object()`, and then send it as an argument in the message as
    /// requested by the protocol.
    ///
    /// Fails if the `ObjectId` is no longer valid.
    ///
    /// This method will not validate that the provided message is valid for given
    /// object, you are responsible for checking it.
    fn send_message(&mut self, id: &Self::ObjectId, msg: Message) -> Result<(), ()>;
    
    /// Receive all pending messages from the server
    ///
    /// Your callback will be called iteratively fro each incoming message from
    /// the server.
    /// The function finally returns `Ok(n)` were `n` is the number of messages
    /// dispatched to your callback.
    ///
    /// If a received message should create a new object, this object will be
    /// automatically be created and its `ObjectId` will be given as part of
    /// the `Message`.
    ///
    /// If no message is pending, it'll not block and immediately return `Ok(0)`.
    fn receive_messages<F>(&mut self, callback: F) -> Result<usize, ReceiveError>
    where F: FnMut(ObjectId, Message));
}

pub trait WaylandFFIClient<ObjData: ObjectData>: WaylandCoreClient<ObjData> {
    /// Initialize this connection in guest mode from a shared `wl_display`
    unsafe fn init_from_external_display(*mut wl_display) -> Self;
    
    /// Get the `wl_proxy` associated to a given wayland object
    fn ptr_from_id(&self, id: &ObjectId) -> Option<*mut wl_proxy>;
    
    /// Get an `ObjectId` representing given `wl_proxy`
    ///
    /// Unless this object was previously created by this library, it'll
    /// be considered as "external". As a result it'll not be possible to
    /// access its `ObjData` (`object_data()` will return `None`), and it'll
    /// not be possible to check that it is still valid when sending requests
    /// to it. You are responsible for ensuring this.
    unsafe fn id_from_ptr(&self, ptr: *mut wl_proxy) -> ObjectId;
    
    /// Take control of the given wayland object
    ///
    /// This object will be initialized as if it was created by this library.
    /// As a result its events will arrive in `Self::receive_message` and it'll
    /// be possible to access its `objData`.
    unsafe fn new_id_from_ptr(&mut self, ptr: *mut wl_proxy) -> ObjectId;
}
```

This is the most generic & low-level API I feel confident about implementing. It can probably be tweaked a little depending on the need, but should be a good starting point for thinking about higher-level API design. The higher-level API would internally own an object implementing this API, and delegate to it the low-level interactions with the socket, mostly.

A similar API can certainly be made for server-side, but I've not yet tried to tackle that. I'd rather see if there's something interesting to do client-side first.

**Comment by tadeokondrak** [comment]
I think getting rid of the libwayland event queue wrapping is a good idea, but I don't use that in the first place. Does it let you do anything you can't do with this design?

**Comment by vberger** [comment]
The event queues are mainly useful when a single Wayland connection needs to be shared between different threads and/or libraries (for example when integrating with Mesa for OpenGL support).

This allows each thread/library to control when the callbacks for its objects are called, which is necessary for thread-safety notably.

**Comment by m-hugo** [comment]
i can see that you mastered rust's syntax and don't need to use rustfmt anymore

**Comment by vberger** [comment]
Dumping some more ideas about it:

We could have a `wayland-interface` crate that would include the definitions of these traits for client/server, as well as maybe a few very minimal helpers around it. This crate would be very light in content, and could quickly be made stable. The API contained in this crate would be the recommended interoperability layer if needed (so ideally be the only thing part of downstream public APIs).

From then, on the one hand, we could have  `wayland-backend-rs` and `wayland-backend-sys`, providing implementations of this trait either in native rust, or using the system libs (and maybe even `wayland-backend-dlopen` ? not sur if it's worth splitting it from `wayland-backend-sys`).

On the other hand, `wayland-client` and `wayland-server` would still exist, and propose more high-level APIs on top of `wayland-interface`. But having `wayland-interface` be the core of interop would make downstream consumers less affected by breaking changes in the API of `wayland-client`: crates using different versions of `wayland_client` would be able to exist in the same binary.

This would also allow experimentations with different wayland APIs (such as `futures`-based for example) without being dependent on support from `wayland-client`.
