### ISSUE TITLE
Replace xcur GPL-3.0 dependency?

### ISSUE THREAD

**Issue by repi** [Smithay/wayland-rs#319]
Ran into that the [`xcur`](https://crates.io/crates/xcur) crate that `wayland-cursor` is using is licensed exclusively under GPL-3.0, is that known and intentional that `wayland-cursor` brings in a copyleft license to an otherwise MIT licensed project?

This can probably be a surprise to users, and limit usage in applications that are not licensed under GPL-3.0.

For example in some of our own closed source applications we use (our) [cargo-deny](https://github.com/embarkStudios/cargo-deny) tool to detect incompatible licenses which is how I ran into this:

![image](https://user-images.githubusercontent.com/1262692/82601577-11004080-9bb0-11ea-8f4c-7e22381622d8.png)

Saw that just 2 days ago PR #318 was created specifically removing [`xcur`](https://crates.io/crates/xcur) in favor of [`xcursor`](https://crates.io/crates/xcursor) which is using the permissive MIT license so would resolve this, which would be great!

If you would be open to it, I can PR and a [GitHub Action with cargo-deny](https://github.com/embarkStudios/cargo-deny-action) to verify only licenses you want to support, quite a few repos that use that for this (and more)

**Comment by vberger** [comment]
> If you would be open to it, I can PR and a GitHub Action with cargo-deny to verify only licenses you want to support, quite a few repos that use that for this (and more)

Oh, I did not know about that. That'd be nice indeed!

**Comment by vberger** [comment]
`wayland-cursor` 0.26.5 is now released without `xcur`.
