### ISSUE TITLE
Try to reduce the dependency graph

### ISSUE THREAD

**Issue by vberger** [Smithay/wayland-rs#321]
the dependency graph of `wayland-rs` is relatively large, which seems a little big for a low-level crate like this. We probably can try to reduce it.

![graph](https://user-images.githubusercontent.com/3009227/82694760-2171f300-9c64-11ea-9197-df5952355cda.png)

**Comment by kchibisov** [comment]
You don't need regex for xcursor-rs crate at all, so it could be all wiped if you're fine taking similar impl from someone under wayland-rs upstream. if you're fine I can send patches.

**Comment by jplatte** [comment]
If regex is removed, it should be easy to get rid of lazy_static too, by replacing it with once_cell which wayland-commons already depends on.

**Comment by kchibisov** [comment]
Basically once can be replaced with another, right, since after regex removal both should be just leafs on this graph afaics, so it's a matter of preference, what suits more, I guess?

**Comment by kchibisov** [comment]
regex was removed.

**Comment by vberger** [comment]
Yes, now the graph looks like that:

![graph](https://user-images.githubusercontent.com/3009227/82991866-9f385480-9ffe-11ea-95c7-5fb014a5f3a0.png)

One I'd like to figure out how to remove would be `parking_lot`, which currently provides a `ReentrantMutex` that `wayland-server` uses to ensure that the ffi to `libwayland-server.so` is never accessed from two different threads conccurently, as the lib as a whole is basically `!Sync`.

**Comment by kchibisov** [comment]
Why `winapi` is on that graph?

**Comment by vberger** [comment]
Mostly because `cargo deps` is not very good at filtering platform-specific dependencies, I think.

**Comment by kchibisov** [comment]
well, we see that nom is a big problem here, maybe one could rewrite xcursor without it :- )

**Comment by jplatte** [comment]
> well, we see that `nom` is a big problem here, maybe one could rewrite xcursor parsing without it :- )

What about this instead? https://github.com/esposm03/xcursor-rs/pull/6 :)

**Comment by kchibisov** [comment]
How much it reduces @jplatte ?

**Comment by jplatte** [comment]
That removes the dependency on `lexical-core`, which means the dependencies on `cfg-if`, `ryu`, `static-assertions`, `arrayvec` and `rustc_version` also disappear as `xcursor` deps (though `wayland-rs` will continue to depend on `cfg-if`).

**Comment by kchibisov** [comment]
The mentioned PR was merged and xcursor version was bumped, so graph could be updated.

**Comment by jplatte** [comment]
By playing with the command line flags until I had this: `cargo deps --no-transitive-deps --subgraph wayland-test wayland-protocols wayland-egl wayland-server wayland-client wayland-cursor wayland-scanner wayland-commons wayland-sys --subgraph-name wayland-rs | dot -Tpng > graph.png`

I got the following updated graph:

![graph](https://user-images.githubusercontent.com/951129/83171800-efa2d580-a116-11ea-81ef-12f188d973c9.png)

**Comment by jplatte** [comment]
By manually excluding proc-macro-only dependencies (`quote`, `proc-macro2`) and target-specific features for platforms that wayland doesn't run on (`winapi`, `cloudabi`, `redox_syscall`, `wasi`), the remaining dependencies that actually contribute to the code size of things that build on wayland-rs are:

![graph](https://user-images.githubusercontent.com/951129/83172829-74422380-a118-11ea-8acf-b9d39f7894c5.png)

Of which I think

* `lazy_static` can trivially be replaced by `once_cell`, then later by `std` potentially (see https://github.com/rust-lang/rfcs/pull/2788)
* `byteorder` might be replaceable with the corresponding functionality in `std` (see https://github.com/rust-lang/rust/issues/52963, stabilized in 1.32.0)

Can't say much about the other ones, but I think there won't be much more to get rid of :)

**Comment by kchibisov** [comment]
tempfile shouldn't be on a graph as well,  I guess, since it was excluded manually from previous graphs, since it's a build time dependency.

**Comment by jplatte** [comment]
![graph](https://user-images.githubusercontent.com/951129/83174470-be2c0900-a11a-11ea-9d54-877c175bf630.png)

**Comment by vberger** [comment]
`tempfile` and `byteorder` are actual `dev-dependencies` of `wayland-client`, and are only used in the examples, so these can be excluded. `cargo deps` does not yet handle correctly dev-deps in workspaces.

**Comment by jplatte** [comment]
Oh, okay, that's what going wrong :)

So all that's left to do it potentially find a replacement for `parking_lot`, and replacing `lazy_static` with `once_cell`? Sounds like this issue could be closed in favor of two new issues that track those specific todos, right?

**Comment by vberger** [comment]
Well, parking-lot will be difficult to get rid of by itself, but will probably disappear when I implement the ideas from #317. I'm not sure if there is much to gain by getting rid of `lazy_static`, as it is a quite pervasive crate, hence there is a high probability that it already appears somewhere else in the dependency graph anyway. So I think we can call it a day for now.
