### ISSUE TITLE
Use pkg-config to link to libwayland

### ISSUE THREAD

**Issue by myfreeweb** [Smithay/wayland-rs#327]
Currently, non-dlopen native C lib usage fails on FreeBSD because libwayland isn't found (all libs are on a non-default path). I would imagine the issue is even harder to solve on systems that have unusual paths like NixOS :)

You really should use [the pkg-config crate](https://docs.rs/pkg-config) in build.rs to link `libwayland-*`.

`dlib` however currently does `#[link(name = $link)]` which is not great. I guess we're not expecting anyone to *rename* these libraries, so it would be "fine" to keep that and just add pkg-config, but ehhh. `#[link]` is not great.

**Comment by vberger** [comment]
> dlib however currently does #[link(name = $link)] which is not great. I guess we're not expecting anyone to rename these libraries, so it would be "fine" to keep that and just add pkg-config, but ehhh. #[link] is not great.

Well, this can be changed tbh. When I wrote it initially `#[link=]` was seemingly the standard thing to do. If it's no longer, well, let's get up to date.
