### ISSUE TITLE
I don't understand the purpose of `Attached`

### ISSUE THREAD

**Issue by timothee-haudebourg** [Smithay/wayland-rs#339]
Hi, In the doc it is said about `Attached`:
> As opposed to Proxy, you can use it to send requests that create new objects.

But I don't see why not. For instance, what stops me from calling `create_surface` on `WlSurface` instead of `Attached<WlSurface>`? In fact I don't see what `Proxy` is even used for?
If I do so, it's unclear to me to which event queue the resulting surface will be attached on...

Could you clarify that for me?

**Comment by vberger** [comment]
You will probably find your answers in the [Smithay book](https://smithay.github.io/book/intro.html), notably sections 1.1.1 and 1.1.2 cover that.

The book is currently WIP, so feedback about is clarity would be quite welcome!

**Comment by timothee-haudebourg** [comment]
OK this is helpful, I like the book so far. But maybe you should add to the actual documentation the fact that creating objects with bare Wayland types will most probably panic?

**Comment by vberger** [comment]
It is there: in 1.1.1:

> - As an Attached<WlFoo>. This form is very similar to the bare WlFoo, but it additionnaly allows you to send requests that create new objects (doing so with a bare WlFoo will panic).

Though maybe it can be made more explicit I guess, but this kind of improvements can be discussed on the [book's repo](https://github.com/smithay/book) I'd say. ;)

**Comment by timothee-haudebourg** [comment]
Oh yes I saw this part, but I meant putting it in the crate's api documentation (of `Attached` for instance) :smile:

**Comment by timothee-haudebourg** [comment]
By the way, on the same subject, I don't really understand why `Attached` and `Main` are not thread same while bare wayland objects are. If I understand correctly, `Attached` symbolizes an object attached to a given queue which will be assigned to the object it creates. It doesn't affect the object in itself. And anyways I can always `Attached::detach` and then `Proxy::attach` the object to move it from/to any thread... Is this undefined behavior? And my understanding is also that the display manages the communication with the server in a thread safe fashion. So I don't really see the safety problem here.

**Comment by vberger** [comment]
> Oh yes I saw this part, but I meant putting it in the crate's api documentation (of Attached for instance)

Oh, it's not there? That's a lack in that case, indeed.

> And anyways I can always Attached::detach and then Proxy::attach the object to move it from/to any thread... Is this undefined behavior?

No, that's perfectly safe and its the intended way to proceed. In order to be threadsafe, wayland-client needs to know to which event queue an object should be assigned when creating it. Attaching a proxy is just a way of defining which queue its children will be assigned to.

As the queues, their tokens, and the attached proxies are not threadsafe, this guarantees that and object is always created on the same thread as the queue that will be dispatching its events, which is the main invariant to preserve.

**Comment by timothee-haudebourg** [comment]
> object is always created on the same thread as the queue that will be dispatching its events

Why is this necessary? I can imagine creating some object in one thread while expecting another thread to take care of handling its events.

**Comment by timothee-haudebourg** [comment]
Thinking about, I think what I want to ask is: If I attach a proxy in two different threads to two different queues. Is the object attached to only a single queue in the end, or is the "attachement" thread local? If I trust the api it should be the later case, right?

**Comment by vberger** [comment]
The attachment is linked to the proxy, not to the wayland object. If your object is attached on two different queues, this means you have two live proxies representing to the same wayland object. The queue on which the children objects are created will thus depend on the proxy you use to create them.

**Comment by timothee-haudebourg** [comment]
OK that clarifies things. Thanks for your time :)
