### ISSUE TITLE
How to manipulate the default event queue?

### ISSUE THREAD

**Issue by timothee-haudebourg** [Smithay/wayland-rs#340]
Each Wayland display should have a default event queue, but I don't see how to manipulate it here?
In the examples you seem to create a new queue right away after the display initialization with `create_event_queue`... Am I missing something?

**Comment by timothee-haudebourg** [comment]
I remember that in a previous version, `Display::connect_to_env` would also return an event queue which I think was the default event queue?

**Comment by vberger** [comment]
This default event queue is a design choice which I removed some time ago, so yes, you need to create the initial event queue.

The rust implementation does not have a default queue at all, and always requires you to create one, so similarly the default queue of libwayland is hidden by wayland-client, and automatically managed behind the scenes to drive the `wl_display`.

**Comment by timothee-haudebourg** [comment]
I see, I didn't realized it was not imposed by the protocol.
