### ISSUE TITLE
QueueToken should be Send

### ISSUE THREAD

**Issue by timothee-haudebourg** [Smithay/wayland-rs#341]
It is quite annoying to be unable to create objects in one thread attached to a queue living in another thread. It is something I was doing using a previous version, and it's blocking me now.

If I understand correctly, doing that would require giving the `QueueToken` of the remote queue to `Proxy::attach`. Which is impossible since `QueueToken` is not `Send`. I feel like it has been done that way so that the filter given to `Main::assign` doesn't need to be `Send`. But it's quite annoying. I feel trapped in my threads.

Instead of making `QueueToken` `Send`, to preserve the good property of `Main::assign` another idea would be to add a `RemoteQueueToken` with `RemoteAttached` and `RemoteMain` for which the filter in `assign` needs to be `Send`.

**Comment by kchibisov** [comment]
it's not Send, because it's not thread safe to do so. You should manage objects only on a thread you've created them. In a multi thread context you may create event queue on a thread you want, that's how everyone is doing so.

**Comment by timothee-haudebourg** [comment]
Could you explain why it is not thread safe?

> that's how everyone is doing so

Well I'm not doing it so. I can't, because in my context I have no guaranties about in which thread some particular code is being executed that needs to create an object (a shared memory pool here). So I am blocked. And it feels like a limitation to me because I don't see why it is not thread safe to assign an object to a remote queue upon creation.

**Comment by vberger** [comment]
> And it feels like a limitation to me because I don't see why it is not thread safe to assign an object to a remote queue upon creation.

The answer is pretty straightforward actually : it is not threadsafe because `libwayland-client.so` does not do any synchronisation around its event queue, hence doing anything with an event queue on an other thread than the one hosting is racy and could corrupt the internal state of the queue. That includes assigning a new object to this queue.

This cannot be made threadsafe in the crate's API without dropping support for using the system-provided libwayland, which would in turn make it impossible to support OpenGL.

**Comment by timothee-haudebourg** [comment]
I see... Ah yes I suppose mesa is using `libwayland-client.so` to implement EGL. Well too bad.

**Comment by vberger** [comment]
Note  that there is a potential way forward regarding this, but it is a long shot : https://github.com/Smithay/wayland-rs/issues/317
