### ISSUE TITLE
Resource::equals() should not check for aliveness

### ISSUE THREAD

**Issue by IntrepidPig** [Smithay/wayland-rs#342]
I think it's unexpected that checking if two resources are equal would return false if they are no longer alive, even if they are indeed the same resource. Is there a reason that it's written like this?

**Comment by vberger** [comment]
This originally comes from a limitation of the system `libwayland`. There might be a way around that, but that'll possibly need some overhead.

**Comment by vberger** [comment]
this is no longer the case in 0.30
