### ISSUE TITLE
Unstable protocols not showing up in docs

### ISSUE THREAD

**Issue by grelltrier** [Smithay/wayland-rs#346]
Is there a trick to get the unstable protocols to show up in the docs or is this a bug? The module "unstable" is not listed in the docs and when I search for documentation of unstable protocols (e.g. `zwlr_layer_surface_v1`) nothing shows up. When I create my own project in which I use the wayland-protocols crate with the feature flag `"unstable_protocols"` and use `cargo doc --open` to view the documentation I can find docs for `zwlr_layer_surface_v1`. Is this intended/expected behavior?

**Comment by kchibisov** [comment]
Unstable protocols are behind a feature flag in a `wayland-protocol`, so you should
`cargo doc --open --features=unstable_protocols` in a wayland-protocols crate.

**Comment by vberger** [comment]
Not sure what is missing, the layer-shell protocol do appear on docs.rs : https://docs.rs/wayland-protocols/0.27.0/wayland_protocols/wlr/unstable/layer_shell/v1/client/zwlr_layer_shell_v1/index.html

Are you activating both the `client` and `unstable_protocols` features?

**Comment by grelltrier** [comment]
I know about setting the features flag. I guess my description of the problem was not good enough.
When you go to [https://docs.rs/wayland-protocols](https://docs.rs/wayland-protocols) the module "unstable" is there and you can find everything. Same when building the docs yourself. When you open [https://crates.io/crates/wayland-protocols](https://crates.io/crates/wayland-protocols) and then click on documentation, you get forwarded to [https://smithay.github.io/wayland-rs/wayland_protocols/](https://smithay.github.io/wayland-rs/wayland_protocols/). There the unstable module is missing and you can also not find them by searching for unstable protocols.

**Comment by grelltrier** [comment]
Changing `documentation = "https://smithay.github.io/wayland-rs/wayland_protocols/"` from the Cargo.toml to `documentation = "https://docs.rs/wayland-protocols"` would presumably fix this but I guess there is a reason why you chose to set your own link so I don't know how this can be fixed

**Comment by vberger** [comment]
Oh, ok I see, thanks for reporting this!

Well yes, looks like we need to change our CI so that it generates the docs with the features enabled, and I think we can forward the `documentation = ` entries in the `Cargo.toml` to point to docs.rs. Docs from the master branch are not the best entry point..
