### ISSUE TITLE
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting

### ISSUE THREAD

**Issue by haraldh** [Smithay/wayland-rs#357]
On Fedora gnome-shell-3.38.1-2.fc33.x86_64

```
$ git clone https://github.com/BrandtM/colourado.git
$ cd colourado
$ cargo run --example preview pastel 16 adjacent
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
Aborted (core dumped)
$ cargo tree -i wayland-client
wayland-client v0.21.13
├── glutin v0.19.0
│   └── pistoncore-glutin_window v0.52.0
│       └── piston_window v0.87.0
│           [dev-dependencies]
│           └── colourado v0.2.0 (/home/harald/git/colourado)
├── smithay-client-toolkit v0.4.6
│   └── winit v0.18.1
│       └── glutin v0.19.0 (*)
├── wayland-protocols v0.21.13
│   └── smithay-client-toolkit v0.4.6 (*)
└── winit v0.18.1 (*)
```

**Comment by kchibisov** [comment]
Update to the latest wayland-rs.

**Comment by haraldh** [comment]
> Update to the latest wayland-rs.

I am just a user... so, it boils down to `pistoncore-glutin_window` still using an old version because of:
https://github.com/PistonDevelopers/glutin_window/pull/179

If only there were bugfix releases of `glutin-0.22` using newer wayland-client versions.

Or maybe even `wayland-client v0.21.14` with a bugfix for this :smiley:

**Comment by kchibisov** [comment]
There's no way to fix it with just bugfix release, it requires breaking release, so we can't do anything about it. Suggest the mentioning project to update to the latest winit/glutin, they have all of that fixed.

**Comment by haraldh** [comment]
Thanks!
