### ISSUE TITLE
Dropping resources kept in filter (quick_assign) move closures

### ISSUE THREAD

**Issue by unrelentingtech** [Smithay/wayland-rs#358]
It's very common to keep state in `move` closures `quick_assign`ed to handle events… and to leak it. In fact client-toolkit's `map_keyboard` assigns a big big object that contains `libxkbcommon` state which shows up prominently in memory leak detectors like `heaptrack`.

It doesn't disappear on `Main<T>::release()` or any destructor, it doesn't disappear when the `Main` is dropped (and I haven't created any other handles, so I guess I could say "when all handles are dropped"?), so the only way I found to drop that stuff is to assign a new closure, e.g. `kb.quick_assign(|_,_,_| ())`. Maybe there should at least be an `unassign` method or something.

**Comment by vberger** [comment]
The closure is supposed to be dropped when then wayland object is destoyed, looks like we have a bug here.

Is it using the rust implementation of the protocol, or using the system libraries ?

**Comment by myfreeweb** [comment]
System.

**Comment by maximbaz** [comment]
I reproduce this using the rust implementation too. Do I understand correctly that the key here, the desired behavior, is to call `.destroy()` (maybe even inside the filter closure), and then the object will be destroyed and all resources will be cleaned up?

**Comment by vberger** [comment]
Indeed, most wayland objects have a destructor request (named `destroy` or `release` depending on the object), and only when it is invoked should the callbacks be dropped.

To you have a small reproducing code that could be used as a test to debug this?

**Comment by maximbaz** [comment]
I'm playing around with `export-dmabuf` in wlroots so my example is based on that, but if this is not something you can run, maybe we can adapt this example to keyboard or something else?

The idea is to prepare a frame, fill it out based on various events, then process it in `Ready` event and discard the frame together with all the data (including the captured variable) and capture the next frame after a short delay.

Let me know if this makes sense or is helpful or not, maybe I can prepare some other example for you?

```rust
use std::rc::Rc;
use wayland_client::protocol::wl_output::WlOutput;
use wayland_client::{Display, GlobalManager, Main};
use wayland_protocols::wlr::unstable::export_dmabuf::v1::client::zwlr_export_dmabuf_frame_v1::Event;
use wayland_protocols::wlr::unstable::export_dmabuf::v1::client::zwlr_export_dmabuf_manager_v1::ZwlrExportDmabufManagerV1;

struct Frame {
    ready: bool,
}

impl Drop for Frame {
    fn drop(&mut self) {
        println!("dropped!")
    }
}

fn capture_frame(dmabuf_manager: Rc<Main<ZwlrExportDmabufManagerV1>>, output: Rc<Main<WlOutput>>) {
    let mut frame = Some(Frame { ready: false });

    dmabuf_manager
        .capture_output(0, &output)
        .quick_assign(move |data, event, _| match event {
            Event::Ready { .. } => {
                // dirty example to capture a variable and do something with it
                frame.as_mut().unwrap().ready = true;

                // trigger resource release, this should make "dropped!" printed but it doesn't
                data.destroy();

                // uncomment this line to *actually* get the resource released
                // frame = None;

                // TODO request another frame after resources are released
                // thread::sleep(time::Duration::from_millis(1000));
                // capture_frame(dmabuf_manager.clone(), output.clone());
            }
            _ => {}
        });
}

fn main() {
    let display = Display::connect_to_env().unwrap();
    let mut event_queue = display.create_event_queue();

    let attached_display = display.clone().attach(event_queue.token());

    let globals = GlobalManager::new(&attached_display);

    event_queue
        .sync_roundtrip(&mut (), |_, _, _| unreachable!())
        .unwrap();

    // for simplicity, jus get the first output
    let output = globals.instantiate_exact::<WlOutput>(1).unwrap();

    let dmabuf_manager = globals
        .instantiate_exact::<ZwlrExportDmabufManagerV1>(1)
        .unwrap();

    capture_frame(Rc::new(dmabuf_manager), Rc::new(output));

    loop {
        event_queue.dispatch(&mut (), |_, _, _| {}).unwrap();
    }
}
```

```toml
[dependencies]
wayland-client = "0.28.3"
wayland-protocols = { version = "0.28.3", features = ["client", "unstable_protocols"] }
```

**Comment by vberger** [comment]
Okay, I can work from this, thanks!

**Comment by vberger** [comment]
Okay so, the thing is, when an object is destroyed, the server then should answer with a `delete_id` event acknowledging the destruction. The Rust implementation actually waits for this event before dropping the closure.

In your example @maximbaz it's just that the server does not send the `delete_id` right away, because it does not automatically flushes its buffer. But if an other stream of requests and events exists, then the destruction is correctly done. For example by replacing your loop with something like:

```rust
    event_queue.dispatch(&mut (), |_, _, _| {}).unwrap();
    event_queue.dispatch(&mut (), |_, _, _| {}).unwrap();
    event_queue.sync_roundtrip(&mut (), |_, _, _| {}).unwrap();
```

However, your example does present a failure to drop when using the system library, so I'll use it for that.

**Comment by vberger** [comment]
Okay, the `use_system_lib` is indeed missing the proper logic to cleanup the state.

It'll be "fun" to add it properly: this is not really a safe thing to do, dropping a closure from within itself.... :sweat_smile:

**Comment by maximbaz** [comment]
Very interesting! Thank you for figuring this out! I confirm your solution is working. Just out of curiosity, why two dispatch calls? 

I'm not sure but maybe it could make sense to update the loop per your suggestion in this example file, it also contains some `quick_assign` calls so might be beneficial to showcase how the resources can be cleaned up in case no other events will come?

https://github.com/Smithay/wayland-rs/blob/b01315eaaf9023902d2816fd44e8d6942ed9a8ac/wayland-client/examples/simple_window.rs#L179-L181

**Comment by vberger** [comment]
Oh, this example was just to ensure the correct amount of messages got dispatched in this specific use. Your loop is perfectly fine in a normal use: an app with other objects sending / receiving events will simply receive the `delete_id` a bit later.

Your minimal example remained stuck because there was no other events to receive that would cause the server to flush its buffer. The `sync_roundtrip()` simply served to force it to flush the buffer and send the `delete_id` event. The two `dispatch()` calls before that ensure all preceding relevant messages were handled. That is all.

**Comment by vberger** [comment]
@unrelentingtech PR #375 should fix the issue for when using the system library, could you test it?

**Comment by unrelentingtech** [comment]
Yep, commented out the `quick_assign`, now no leak with #375 :+1:

before:
![Screen_2021-02-16-22:20:24](https://user-images.githubusercontent.com/208340/108111427-b6940200-70a5-11eb-8758-c0a1d16af019.png)

after:
![Screen_2021-02-16-22:22:30](https://user-images.githubusercontent.com/208340/108111424-b5fb6b80-70a5-11eb-9225-edb2b456e005.png)
