### ISSUE TITLE
Segfault in libwayland-client

### ISSUE THREAD

**Issue by Imberflur** [Smithay/wayland-rs#359]
If the wayland clipboard from [`window_clipboard`](https://docs.rs/window_clipboard/0.1.3/window_clipboard/) is dropped while using `winit` there is a segfault in `libwayland-client` when the mouse is moved (could also be with other window events).

See https://gitlab.com/veloren/veloren/-/issues/855
[gdb-backtrace.txt](https://github.com/Smithay/wayland-rs/files/5626565/gdb-backtrace.txt)

**Comment by kchibisov** [comment]
Could you test https://github.com/Smithay/smithay-clipboard/pull/31 ? I've tested it with some veloren that was crashing before,and it's no longer does that if you patch clipboards to use this branch.

**Comment by Imberflur** [comment]
I had the user that was seeing the issue test a veloren build with this. Our `Cargo.lock` was pointing to `smithay-clipboard 0.5.2` so before patching in the branch I needed to update the minor version of `clipboard_wayland` https://docs.rs/clipboard_wayland/0.1.2/clipboard_wayland/ which allowed updating `smithay-clipboard`. To be thorough I made a build for testing with the updated deps before patching in your branch.

These are the builds:
```rs
older clipboard crate: https://gitlab.com/veloren/veloren/-/jobs/896170352/artifacts/download
updated clipboard crate: https://gitlab.com/veloren/veloren/-/jobs/896176166/artifacts/download
updated clipboard crate with fix: https://gitlab.com/veloren/veloren/-/jobs/896176086/artifacts/download
```
The results were:
> older clipboard crate build segfaults, updated clipboard crate build does not segfault, and updated clipboard crate with fix build does not segfault

So it seems like updating might have had an effect. :confused: 

My changes for these builds can be found here (each commit corresponds to one of the builds listed above): https://gitlab.com/veloren/veloren/-/merge_requests/1602

**Comment by Imberflur** [comment]
I think this is resolved.
