### ISSUE TITLE
Client::kill with native impl will not supply DispatchData

### ISSUE THREAD

**Issue by nbdd0121** [Smithay/wayland-rs#365]
When I tried to run anvil from smithay in winit mode with Xwayland (with patch in https://github.com/Smithay/smithay/issues/25 applied), I noticed that closing the window will trigger a panic.

Some tracing showed that the issue is caused by https://github.com/Smithay/smithay/blob/4d012e17a0b37cf8fe39530df0948fafa371b026/src/xwayland/xserver.rs#L184. The DispatchData supplied is empty. Further digging shows that in pure Rust impl, the destructors are only called with `Display::flush_clients`, which will fill DispatchData, but for native impl the client destructors are called right away when invoking `Client::kill`, which does not take any DispatchData.

**Comment by vberger** [comment]
Yes, that is an API inconsistency. I don't think there is any good way to make the dispatch data available to the client destructors when using the system lib though. Probably the dispatch-data argument should just be removed from the closure.

Note btw that this problem in xwayland has already been reported there : https://github.com/Smithay/smithay/issues/245
