### ISSUE TITLE
Protocol error 3 on object xdg_surface@9: xdg_surface has never been configured

### ISSUE THREAD

**Issue by jwinarske** [Smithay/wayland-rs#367]
I'm jumping into wayland-rs for a series of projects, and am looking at running the simple_window example with xdg_wm_base, and am hitting a protocol error.

My simple_window.rs is [here](https://github.com/jwinarske/wayland-rs/blob/master/wayland-client/examples/simple_window.rs)

Can someone take a look and provide some comments?

Thanks,
Joel

```
[wayland-client] Protocol error while reading events: Protocol error 3 on object xdg_surface@9: xdg_surface has never been configured
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 71, kind: Other, message: "Protocol error" }', wayland-client/examples/simple_window.rs:165:92
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /home/joel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: simple_window::main
             at ./examples/simple_window.rs:165:5
   5: core::ops::function::FnOnce::call_once
             at /home/joel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jwinarske** [comment]
[C pattern](https://github.com/wayland-project/weston/blob/master/clients/simple-egl.c#L358)

**Comment by vberger** [comment]
The `xdg_wm_base` protocol requires that you wait until you have received a first `xdg_surface.configure` event before attaching a buffer to your surface, not waiting is a protocol error, which you are encountering here.

Uless you really need to handle all this plumbing by yourself, I'd recommend using [SCTK](https://github.com/Smithay/client-toolkit),which handles a significant part of the work for you,aand has a few fleshed-out examples. You can also have a look at the [Smithay book](https://smithay.github.io/book),wwhich iis sstill vvery WIP but should contain enough to help you get started.

**Comment by jwinarske** [comment]
Yeah I need lower level stuff for my job.

I created PR https://github.com/Smithay/wayland-rs/pull/368

Thanks!

**Comment by Stargateur** [comment]
on the last commit ddd92dcaf this still happen. I just wanted to try out the example but I have the same error message.

**Comment by vberger** [comment]
Should be good now, one line was missing.

**Comment by Stargateur** [comment]
yep it's fix, thank you very much, finally after hours of installer on my archlinux arm this work xd (even if the compositor crash often haha)
