### ISSUE TITLE
[wl_output] Not seeing scale factor and done events

### ISSUE THREAD

**Issue by jwinarske** [Smithay/wayland-rs#369]
I only see geometry and mode events.  Scale factor, and done event are not generated.

[Example](https://github.com/Smithay/wayland-rs/pull/368/files#diff-781225a9e75db22a2fd4b445c2a8c13264a22c14b5bba885fcccbb199a4ca258R82)

Using the same compositor (Fedora 33 stock) with Weston C client code, I do get all four events as expected.

**Comment by vberger** [comment]
You are binding version 1 of the global (the argument given to `instantiate_exact`), while these events were introduced in version 2.

**Comment by jwinarske** [comment]
Ah!  Cool, that fixed it.
