### ISSUE TITLE
[question] C pointers

### ISSUE THREAD

**Issue by jwinarske** [Smithay/wayland-rs#370]
I'm implementing a simple window to overlay a video window (gstreamer waylandsink).  I have both rendering, only I need to provide a "C" pointer of the surface to gstreamer/gst_video_overlay_set_window_handle().

I recall seeing something about using system lib shims if needing GL context C pointer.  Are there any examples for this?

Thanks,
Joel

**Comment by Drakulix** [comment]
You need to enable the [`use_system_lib` feature](https://github.com/Smithay/wayland-rs/blob/master/wayland-client/Cargo.toml#L31). After that you should be able to use [`c_ptr()`](https://docs.rs/wayland-client/0.28.3/wayland_client/struct.Proxy.html#method.c_ptr) and pass that to gstreamer.

Btw, you might want to join [our matrix chat](https://github.com/Smithay/wayland-rs#chat-and-support) for these kinds of questions. You likely get an answer quicker (and more consistently) and avoid creating issues for usability questions.

**Comment by jwinarske** [comment]
@Drakulix  Sure thing thanks
