### ISSUE TITLE
incompatible with NVIDIA/egl-wayland

### ISSUE THREAD

**Issue by wez** [Smithay/wayland-rs#374]
Analysis in the issue I filed with them over here:
https://github.com/NVIDIA/egl-wayland/issues/34

The gist of it is that `/*Rust*/ &wayland_client::protocol::wl_surface::wl_surface_interface != /*C*/ &wl_surface_interface` and that causes `BAD_NATIVE_WINDOW` to be returned from the nvidia egl wayland implementation.

It's not clear to me whether that's an nvidia bug, or if this might be a surprising situation when the `use_system_lib` is enabled in the rust client; I can see arguments for both.

If those interface globals could alias those from the system lib when `use_system_lib` is enabled it might reduce some surprises, but I'm no wayland expert!

**Comment by tadeokondrak** [comment]
How libwayland handles this (internal helper function):
```c
int
wl_interface_equal(const struct wl_interface *a, const struct wl_interface *b)
{
	/* In most cases the pointer equality test is sufficient.
	 * However, in some cases, depending on how things are split
	 * across shared objects, we can end up with multiple
	 * instances of the interface metadata constants.  So if the
	 * pointers match, the interfaces are equal, if they don't
	 * match we have to compare the interface names.
	 */
	return a == b || strcmp(a->name, b->name) == 0;
}
```
