### ISSUE TITLE
simple_window example endianness

### ISSUE THREAD

**Issue by Stargateur** [Smithay/wayland-rs#385]
https://github.com/Smithay/wayland-rs/blob/e0b35a6f2bde7efec10eb1d51bfa194c62313672/wayland-client/examples/simple_window.rs#L55

simple_window example use [`u32::to_ne_bytes()`](https://doc.rust-lang.org/std/primitive.u32.html#method.to_ne_bytes) that return the native endian representation array of the integer but the documentation of [`Argb8888`](https://docs.rs/wayland-client/0.28.5/wayland_client/protocol/wl_shm/enum.Format.html#variant.Argb8888) says:

> Argb8888
>   32-bit ARGB format, [31:0] A:R:G:B 8:8:8:8 little endian

Confirmed by official wayland doc about [`Argb8888`](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_shm-enum-format):

> argb8888
>   0 - 32-bit ARGB format, [31:0] A:R:G:B 8:8:8:8 little endian

So, shouldn't the example on the contrary use [`u32::to_le_bytes()`](https://doc.rust-lang.org/std/primitive.u32.html#method.to_le_bytes) ?

**Comment by vberger** [comment]
Good point, I guess I mixed up with the wayland wire format, which is specified to be native-endian. :sweat_smile:
