### ISSUE TITLE
virtual frame buffer?

### ISSUE THREAD

**Issue by lzunsec** [Smithay/wayland-rs#394]
Hi, I'm a bit confused. Can I run this and render things into a framebuffer, connected to no displays?

I was thinking about running this on a VM and then accessing this framebuffer from outside the VM, just for learning purposes. Or maybe access this framebuffer from a VNC server and access this server from outside the VM.

Is there a tutorial on how to run this in a framebuffer, and also how to render something to this frame buffer? Maybe xeyes (or wayland_eyes)?

Thank you very much!

**Comment by vberger** [comment]
Hi,

This is a library solely for using the wayland protocol, so it does not handle anything about rendering, framebuffers, or VMs, so I'm guessing you're on the wrong repository maybe? Was this issue intended for [smithay](https://github.com/Smithay/smithay) maybe?
