### ISSUE TITLE
GTK fails to read data from the display

### ISSUE THREAD

**Issue by DemiMarie** [Smithay/wayland-rs#404]
When the Rust server implementation is used, GTK clients eventually fail to read from the display (with `EINVAL`).  This problem is reasonably reproducible and goes away if the `use_system_lib` feature is enabled.

**Comment by ids1024** [comment]
Do you still see issues with this, or can it be closed?

This doesn't really seem to be an issue in cosmic-comp, without the `client_system` feature.

**Comment by DemiMarie** [comment]
Closing since I have not used Smithay in quite a while.  My use-case required a software renderer which Smithay did not have at the time.
