### ISSUE TITLE
Is listed IRC info still accurate?

### ISSUE THREAD

**Issue by atouchet** [Smithay/wayland-rs#420]
In the Readme it states:

The chat room is bridged over multiple chat servers, here are 3 options on how to connect to the chat:

    #smithay on Freenode IRC

Is this still accurate?

**Comment by i509VCB** [comment]
Nope, we have moved to libera.chat

**Comment by vberger** [comment]
Indeed, this was outdated. This is now fixed in 1512878773f1b3fc440dc9f009c0055ca29ffede

**Comment by atouchet** [comment]
@vberger there's another outdated reference in https://github.com/Smithay/smithay-clipboard/blob/master/CONTRIBUTING.md too.
