### ISSUE TITLE
Got `NoCompositorListening` from `Display::connect_to_env()`

### ISSUE THREAD

**Issue by ArturKovacs** [Smithay/wayland-rs#421]
Using `wayland-client = { version = "0.29", default_features = false,  features = ["use_system_lib"] }`

Various info of my setup:
```
artur@orange:~$ screenfetch 
                          ./+o+-       artur@orange
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.11.0-43-generic
           .++ .:/++++++/-.+sss/`      Uptime: 2h 8m
         .:++o:  /++++++++/:--:/-      Packages: 1875
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.0.17
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 3.36.5
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Yaru
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 52G / 141G (39%)
           .o:`.syhhhhhhh/.oo++o`      CPU: AMD Ryzen 5 4600H with Radeon Graphics @ 12x 3GHz
               /osyyyyyyo++ooo+++/     GPU: AMD RENOIR (DRM 3.40.0, 5.11.0-43-generic, LLVM 12.0.0)
                   ````` +oo+++o\:     RAM: 5642MiB / 7316MiB
                          `oo++.      
artur@orange:~$ mutter --version
mutter 3.36.9
Copyright © 2001-2011 Havoc Pennington, Red Hat, Inc., and others
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
artur@orange:~$ echo $WAYLAND_SOCKET

artur@orange:~$ echo $WAYLAND_DISPLAY
wayland-0

```

**Comment by vberger** [comment]
Is the wayland socket at `$XDG_RUNTIME_DIR/wayland-0`, as expected? Given your env variable is set, it looks like wayland-rs failed to connect to that socket.

**Comment by ArturKovacs** [comment]
> Is the wayland socket at `$XDG_RUNTIME_DIR/wayland-0`, as expected?

How would one check that? I have no experience working with wayland.

**Comment by i509VCB** [comment]
> > Is the wayland socket at `$XDG_RUNTIME_DIR/wayland-0`, as expected?
> 
> How would one check that? I have no experience working with wayland.

If you run `cd $XDG_RUNTIME_DIR` and run ls you should see a file named `wayland-0`

**Comment by ArturKovacs** [comment]
```
artur@orange:~$ ls -l $XDG_RUNTIME_DIR | grep wayland
srwxrwxr-x 1 artur artur   0 Dec 21 20:12 wayland-0
-rw-rw---- 1 artur artur   0 Dec 21 20:12 wayland-0.lock
srwxrwxr-x 1 artur artur   0 Dec 21 20:36 webkitgtk-wayland-compositor-a2588254-5caa-47dd-a77c-e8d3d51997f5
-rw-rw---- 1 artur artur   0 Dec 21 20:36 webkitgtk-wayland-compositor-a2588254-5caa-47dd-a77c-e8d3d51997f5.lock
artur@orange:~$ 

```

**Comment by vberger** [comment]
I must admit I don't understand why it cannot open your socket.

I strongly suspect the `connect()` invocation fails, may you can add a `println!()` here, to display the error that is currently discarded (but really should not be)?

**Comment by ArturKovacs** [comment]
I couldn't reproduce this in a minimal example. If I had to guess, it was due to me using a crate with a few "patch" sections, and cargo might have gotten confused.

I'm closing this as it doesn't seem to be an issue coming from this crate.

**Comment by guhwanbae** [comment]
Hi, @ArturKovacs , @vberger ,
I also had this problem while running a wayland client program. wayland-client concatenates XDG_RUNTIME_DIR and WAYLAND_DISPLAY to make a socket path. WAYLAND_DISPLAY is normally the name of a socket.

https://github.com/Smithay/wayland-rs/blob/f6bf1cad5951b3d3042fc5f1f5721905a7deb24e/wayland-client/src/display.rs#L150

Some client programs uses "wayland-0" as a fallback of WAYLAND_DISPLAY. But, if it is not set, wayland-client reports a NoCompositorListening.

After setting a WAYLAND_DISPLAY variable, it works! :)

**Comment by vberger** [comment]
> Some client programs uses "wayland-0" as a fallback of WAYLAND_DISPLAY.

FYI, this is a behavior that is considered deprecated (but is kept in libwayland-client for backward compatibility) because it can cause some very surprising results when multiple compositors are running on the same machine (like an app not starting in the compositor the user would expect to). Several compositors now avoid using `wayland-0` for this reason. This is why wayland-rs decided to not implement this fallback at all.
