### ISSUE TITLE
crates.io docs don't match API for wayland-client

### ISSUE THREAD

**Issue by spencerwhite** [Smithay/wayland-rs#465]
Hey, I just wanted to notify y'all that the [crates.io](https://crates.io/crates/wayland-client) page contains a link to innacurate [docs](https://smithay.github.io/wayland-rs/wayland_client/). This may make it diffucult for new users to get started with the crate.

**Comment by kchibisov** [comment]
The link seems correct? Though, crates-io is pulling latest stable release, and not alphas. But right now wayland-rs version is https://crates.io/crates/wayland-client/0.30.0-alpha6

**Comment by spencerwhite** [comment]
Hm, I'm definitely using `0.29.4` in my crates.toml and cargo keeps complaining that `wayland-client` doesn't exist. Also, if I use `cargo doc` to generate the docs for `0.29.4` on my own end, I get something that looks totally different:
![image](https://user-images.githubusercontent.com/7970508/158310502-f3444370-cdba-474d-b175-fb1ff64a93e7.png)

**Comment by vberger** [comment]
Indeed, the crate.io documentation metadata points to the master branch docs hosted on `https://smithay.github.io/`, and should be updated to point to docs.rs instead.

**Comment by vberger** [comment]
In the meantime @spencerwhite , you can find the docs you seek on https://docs.rs/wayland-client

**Comment by vberger** [comment]
Fixed in 3b4178c1eccc1518ef6a80d7e1a88fee0ed4535e, will be corrected in the next release.
