### ISSUE TITLE
Unclear phrasing in docs

### ISSUE THREAD

**Issue by wildwestrom** [Smithay/wayland-rs#525]
https://github.com/Smithay/wayland-rs/blob/master/wayland-client/src/conn.rs

> The two main an simple app as for the [Connection](https://docs.rs/wayland-client/0.30.0-beta.8/wayland_client/struct.Connection.html) are:

I don't know what this is supposed to mean.

**Comment by vberger** [comment]
Yup, there's a missing word and a few typos... That's supposed to read something like

> The two main uses a simple app has for the Connection are:
