### ISSUE TITLE
No registry events after upgrading beta.8 to beta.9

### ISSUE THREAD

**Issue by WhyNotHugo** [Smithay/wayland-rs#567]
I upgraded a project from beta.8 to beta.9, and now I get no registry events on startup. Output with `WAYLAND_DEBUG=1` just shows:

```
[1663881024.704147] -> wl_display@1.get_registry (wl_registry@2)
[1663881024.704200] -> wl_display@1.sync (wl_callback@3)
```

The same code works fine with beta.8. Here's the exact diff of the upgrade:

https://git.sr.ht/~whynothugo/shotman/commit/71522a026eb7ac53c7a4d40783e2b8f7896a1d83

Are there any API breaking changes that I should be aware of? I can't find any PRs or obvious changes to registry that could result in this behaviour. Any ideas?

This particular case can be reproduced with:

```sh
git clone https://git.sr.ht/~whynothugo/shotman
cd shotman
git checkout 71522a026eb7ac53c7a4d40783e2b8f7896a1d83
WAYLAND_DEBUG=1 cargo run -- output -v
```

**Comment by i509VCB** [comment]
Beta 9 had a bug that made event queues wait forever. Beta 10 should fix it.

**Comment by WhyNotHugo** [comment]
Oh, I can upgrade to beta.10 after https://github.com/Smithay/client-toolkit/commit/1cc11af8538040f46173bf021ac079c342ddeebb. Thanks.
