### ISSUE TITLE
Implement `HasRawDisplayHandle` for Connection

### ISSUE THREAD

**Issue by i509VCB** [Smithay/wayland-rs#573]
Since raw-window-handle has now split between display and window handles, it may be convenient for library users to be able to get a raw window handle.

**Comment by elinorbgr** [comment]
This is implemented for `Backend` already, and I don't think it'd be possible to bring that to the `Connection` directly without introducing a feature on wayland-client for matching the backend type (sys or rs), so I think we'll stay at the current state.
