### ISSUE TITLE
Make wayland-sys tracked separately

### ISSUE THREAD

**Issue by kchibisov** [Smithay/wayland-rs#575]
The wayland-sys is more or less stable crate, it doesn't change that much, however its version is artificially bumped making other crates using just wayland-sys incompatible with newer versions using newer wayland-sys.

If we had stable wayland-sys which isn't get bumped with other wayland-rs crates it would simplify cases where multiple crates use different wayland-sys bindings.

**Comment by vberger** [comment]
The overall goal is to split the version numbering of all of the wayland-rs crates once the full 0.30 is out, which really should be done soon, I agree.

**Comment by kchibisov** [comment]
I think you can have `0.30` for wayland-sys earlier? We can have wayland-sys 0.30 so we can use apps depending on it with wayland-rs betas right now. I don't think waiting for other crates to come to 0.30 will provide anything other than creating unnecessary burden for downstream.

**Comment by ids1024** [comment]
> I think you can have 0.30 for wayland-sys earlier?

Or if there aren't any breaking API changes in wayland-sys, reduce the version back to `0.29.x` and release it, updating the other wayland-rs 0.30.0 crates to use that version.

**Comment by elinorbgr** [comment]
I guess I can release the 0.30 for wayland-sys yeah, it's the most stable of all.

**Comment by kchibisov** [comment]
Thanks, @elinorbgr!

**Comment by elinorbgr** [comment]
wayland-sys 0.30 is released.
