### ISSUE TITLE
Compile wayland-rs/wayland-backend without linking to wayland-sys

### ISSUE THREAD

**Issue by madushan1000** [Smithay/wayland-rs#582]
I'm trying to get wayland-client/wayland-protocols crates(v0.30.0-beta.13) working as a aosp rust module. And I would like to not link to wayland system modules at all. But there is a dependency wayland-client -> wayland-backend -> wayland-sys -> c wayland lib. Due to these lines in wayland-backend 
https://github.com/Smithay/wayland-rs/blob/master/wayland-backend/src/protocol.rs#LL5
https://github.com/Smithay/wayland-rs/blob/master/wayland-backend/src/protocol.rs#L150
Can these be put behind a feature flag without breaking anything?

**Comment by elinorbgr** [comment]
If you use wayland-backend without enabling its `system_*` cargo features, it depends on wayland-sys without enabling its cargo features either. In that case, wayland-sys only contains type definitions, and does not link to anything.

**Comment by madushan1000** [comment]
I tried it and it works for the help :)
