### ISSUE TITLE
Use `BorrowedFd` for requests/events instead of `RawFd`

### ISSUE THREAD

**Issue by ids1024** [Smithay/wayland-rs#592]
Currently events a client receives with an fd use `OwnedFd`, while events the client sends use `RawFd`. In server code it's the same but reversed.

As a result of this, functions like `WlShm::create_pool` violate IO safety rules since the function takes and operates on a `RawFd`, but the function is not marked `unsafe`.

This should instead use a `BorrowedFd`, but this is complicated from a lifetime perspective. I think `wayland_client::Proxy`'s `Request` and `wayland_server::Resource`'s `Event` would need to use GATs generic over a lifetime? This isn't possible as long as wayland-rs targets Rust < 1.65.0 though.

**Comment by vberger** [comment]
Yes, this lifetime constraint is the exact reason why I left the `RawFd` at this place.

**Comment by ids1024** [comment]
I guess this is something for 0.31.0, by which point wayland-rs's Rust MSRV will probably be new enough to use GATs.

**Comment by elinorbgr** [comment]
This is now done.
