### ISSUE TITLE
Add wayland-backend features control to wayland-client.

### ISSUE THREAD

**Issue by ngortheone** [Smithay/wayland-rs#614]
`wayland-backend` crate has an option to not use system wayland libraries and use pure rust implementation.

Unfortunately `wayland-client` does not expose controls to select features for `wayland-backend`, which results in my project depending on `wayland-sys` no matter what

`cargo tree -e features`
```
myproject v0.1.0
├── wayland-backend v0.1.1
│   ...
│   └── wayland-sys feature "default"
│       └── wayland-sys v0.30.1
│           ├── dlib feature "default"
│           │   └── dlib v0.5.0
│           │       └── libloading feature "default"
│           │           └── libloading v0.7.4
│           │               └── cfg-if feature "default" (*)
│           └── log feature "default"
│               └── log v0.4.17
│                   └── cfg-if feature "default" (*)

```

Please add controls to `wayland-client` to disable default features (or select features) in `wayland-backend`

**Comment by kchibisov** [comment]
There're no default features. It means that something in your project is forcing the system library for whatever reason.

If you think that you don't depend on the system-library anywhere add
```
wayland-backend = { version = "0.1.0", default_features = false, features = [], optional = true }
```

**Comment by elinorbgr** [comment]
> `wayland-backend` crate has an option to not use system wayland libraries and use pure rust implementation.

Yes, as @kchibisov described, it's actually the opposite: by default it uses the pure rust implementation, and the use of system libraries needs to be enabled by activating the `client_system` cargo feature on `wayland-backend`.

So you must have something else in your project that depends on `wayland-backend` activating its `client_system` feature.

**Comment by ngortheone** [comment]
Here is my `Cargo.toml`

```
[package]
name = "myproject"
version = "0.1.0"
edition = "2021"

[dependencies.wayland-client]
version = "*"
default-features = false
features = []
```

And the code I have is copied from this getting started example https://docs.rs/wayland-client/latest/wayland_client/#getting-started-example

What can be triggering `client_system`?

**Comment by Drakulix** [comment]
> Also am I misreading this or wayland-backend unconditionally depends on wayland-sys?

Yes it does, but only for a few definitions.
If neither `wayland-sys`' `client` nor `server` features are activated, the crate won't contain any actual bindings or require any libwayland libraries.
