### ISSUE TITLE
wayland-client: duplicate dependencies with `calloop` feature

### ISSUE THREAD

**Issue by bryceberger** [Smithay/wayland-rs#630]
`wayland-client =0.30.2 ["calloop"]` depends on
- `calloop ^0.10.5`
- `nix ^0.26`

`calloop ^0.10.5` depends on
- `nix ^0.25`

**Comment by elinorbgr** [comment]
Following #638 the calloop integration in wayland-client is removed. The two crates are still too much of a moving target API-wise to tie their versions together like that.
