### ISSUE TITLE
Delay in rendering frame while resizing

### ISSUE THREAD

**Issue by hungrier-brain** [Smithay/wayland-rs#631]
In the examples for Smithay client-toolkit, when I resize the example windows (for example sample_window), there is a noticeable delay in rendering. Is there any fix/workaround?

**Comment by kchibisov** [comment]
Have you tried a release build? The default examples are pretty slow because they set each pixel individually.

**Comment by hungrier-brain** [comment]
Yes, it has significantly reduced the lag. Thank you very much.
