### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by bmariuszb** [Smithay/wayland-rs#649]
Please add to wayland_client documentation a note to WlSurface on how it is usually created. Maybe WlSurface isn't that important, because anyone can just search surface and they will find pretty easily create_surface method, but adding note on creating WlShm and WlCompositor would be helpfull. I just know know this crate for about 2-3 days and so far I assume you don't create WlCompositor, instead you use bind from registry to get those objects already created.

**Comment by elinorbgr** [comment]
The documentation of the protocol objects is generated from the XML specification of the protocol, and not hand-written, so we cannot really change it easily.

There is a project of a "tutorial book" on using wayland-rs / SCTK and Smithay here https://github.com/Smithay/book/ and browsable here https://smithay.github.io/book/intro.html , unfortunately it is still very "work in progress". The part 1.1 is up to date though.

However I advise you to find a general tutorial about the Wayland protocol itself, these bindings are made in the assumption that you are somewhat familiar with it. You can for example take as a reference the https://wayland-book.com/ , it is written for the C language, but what it says about the Wayland protocol itself is universal.

**Comment by bmariuszb** [comment]
I didn't know these are just bindings. 
> not hand-written, so we cannot really change it easily.

In that case I think you can close this issue.
