### ISSUE TITLE
Reading the state of a key at any point in time out of scope?

### ISSUE THREAD

**Issue by TomVer99** [Smithay/wayland-rs#670]
Hi there,
I was trying to read the state of any key, something like GetKeyState on Windows. But I had trouble finding something here that would allow me to do so. I heard someone say that it was out of scope but I wanted to make sure.

So is this out of scope? Is it not implemented yet?

Thanks,

**Comment by elinorbgr** [comment]
Such kind of state tracking is out of scope for wayland-rs, which only provides bindings to the protocol API, and nothing more. The way the protocol works is that you are notified whenever a key changes state, and you are responsible for tracking which keys are currently pressed if you need to.

Such a helper might be in scope for [SCTK](https://github.com/Smithay/client-toolkit/) instead.

**Comment by TomVer99** [comment]
> Such kind of state tracking is out of scope for wayland-rs, which only provides bindings to the protocol API, and nothing more. The way the protocol works is that you are notified whenever a key changes state, and you are responsible for tracking which keys are currently pressed if you need to.
> 
> Such a helper might be in scope for [SCTK](https://github.com/Smithay/client-toolkit/) instead.

Thank you for the information and redirect!
