### ISSUE TITLE
wayland-sys vendor feature (request for a `wayland-src` crate)

### ISSUE THREAD

**Issue by samcday** [Smithay/wayland-rs#706]
(see https://github.com/rust-windowing/winit/issues/1818#issuecomment-1986787669 for more context)

As it currently stands, wayland-rs on musl is fraught with difficulty. TL;DR:

 * The `dlopen` feature can never work for musl targets, because the rust compiler produces statically linked binaries for musl targets, and `dlopen` explicitly does not work for static musl.
 * Without dlopen, wayland-sys falls back to linking against system wayland libs, which is a mess for just about any cross compile environment.

The openssl crate had this issue for years, and then they added the [`openssl-src`](https://docs.rs/openssl/latest/openssl/#vendored) crate to support building + linking openssl.

I'm proposing that `wayland-sys` offer the same: a `vendor` crate feature that, when enabled, builds and statically links the wayland-client/server libs.

**Comment by samcday** [comment]
Never mind, my understand was faulty. I wasn't properly specifying `RUSTFLAGS=-Ctarget-feature=-crt-static` when building for musl targets. Now dlopen is working fine ;)

**Comment by ids1024** [comment]
For reference, statically linking libwayland will likely run into issues if you want to use OpenGL or Vulkan, since the driver which is normally dynamically loaded needs to be using the same libwayland.
