### ISSUE TITLE
how to convert a wl_surface pointer to WlSurface

### ISSUE THREAD

**Issue by Sherlock-Holo** [Smithay/wayland-rs#708]
I get the `wl_surface` pointer from https://docs.rs/raw-window-handle/0.6.0/raw_window_handle/struct.WaylandWindowHandle.html#structfield.surface

however when I want to use `wayland-client` `WlSurface`, I didn't find a function or method to convert the `wl_surface` pointer to `WlSurface`

is there any way to do this job? can I just convert the pointer to `*mut WlSurface` and then convert to `&mut WlSurface`

**Comment by ids1024** [comment]
I guess the generated API docs are build without the `wayland-backend/client_system` feature, so `ObjectId::from_ptr` isn't listed. You'll need that feature, then `ObjectId::from_ptr`, then `WlSurface::from_id` (from the `Proxy` trait).

https://github.com/rust-windowing/softbuffer/blob/5c7a2099e00a6c5e1e8eb3f65f05596a3f1c6db2/src/backends/wayland/mod.rs#L159-L167 for instance creates a `WlSurface` from a raw-window-handle.

**Comment by Sherlock-Holo** [comment]
thank you, it solved my problem
