### ISSUE TITLE
Mouse Motion Event

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/wayland-rs#87]
So I was just playing around with mouse events and noticed something weird.

If I run the window example the mouse motion event doesn't work.
However, if I add a second `surface.commit()` right after the first one (https://github.com/vberger/wayland-client-rs/blob/master/wayland-client/examples/simple_window.rs#L115) it does work.

I am currently running into this problem with my own program that I need to do the first commit twice for mouse events to work and I am not sure if this is a bug, since it's even present in the example.

I've tested this with Sway if that matters.

**Comment by vberger** [comment]
It might be a bug with sway, because for the me example works out of the box on weston.

I'll try it on sway too, to compare.

**Comment by chrisduerr** [comment]
So I tested this with orbment and had the same issue. Apparently it's a problem with wlc?

**Comment by vberger** [comment]
As WLC is being deprecated, I'll close this.
